### ISSUE TITLE
Playground

### ISSUE THREAD

**Issue by wdibi** [IBAnimatable/IBAnimatable#102]
There is an issue of not being able to import IBAnimatable into the playground when following your instructions.

**Comment by lexrus** [comment]
1. Open IBAnimatableApp.xcodeproj
2. Select IBAnimatable Framework scheme and build it with command + b
3. Select the first IBAnimatable.playground
4. Have fun

![ibplayground](https://cloud.githubusercontent.com/assets/219689/13034403/73b4641c-d36f-11e5-8428-5de9df39397d.jpg)

**Comment by wdibi** [comment]
Thanks!

**Comment by lexrus** [comment]
@JakeLin Is this the correct process to open the Playground? Have you described others somewhere?

**Comment by JakeLin** [comment]
I describe it in README.md, but I think I should add those step you mentioned above to make it clearer.

**Comment by damtsnkff** [comment]
I'd add a little trick in case someone else (like me) struggle even after the following steps didn't work : After doing all the step above, delete the line 'import IBAnimatable', and re-type it with the autocompletion.
