### ISSUE TITLE
Move GIF screencasts into a issue

### ISSUE THREAD

**Issue by lexrus** [IBAnimatable/IBAnimatable#103]
So that users can clone this repo faster.

Have you ever noticed that IBAnimatable.gif is a 7.1MB file?

**Comment by JakeLin** [comment]
Thanks, I noticed that before and created a misc project to store those stuff. Have moved them to Misc project in #105

**Comment by lexrus** [comment]
Jake, you can create an issue and close it. Upload all images in this issue. They will be permanently exist. That's what I did.
https://github.com/lexrus/VPNOn/issues/1

**Comment by JakeLin** [comment]
Thanks, learning new thing every day. I think I still need to remove them from the repo, right? If yes, I merge #105

**Comment by lexrus** [comment]
Yes, you're right. :+1:

**Comment by tbaranes** [comment]
Awesome tips @lexrus! Didn't know that.
