### ISSUE TITLE
Configurable `Polygon` mask

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#112]
Add parameter to configure the sides of  `Polygon` mask like `Star`.

Currently, it generate random sides every time.

```
  public func maskPolygon() {
    let polygonPath = maskPolygonBezierPath(Int(arc4random_uniform(10) + 3))
    drawPath(polygonPath)
  }
```

Should take have sides parameter like `public func maskPolygon(sides: Int = 6)`

**Comment by tbaranes** [comment]
Agree 👍
