### ISSUE TITLE
README.md correction - Shadows render correctly in IB

### ISSUE THREAD

**Issue by leonardbonfils** [IBAnimatable/IBAnimatable#116]
In your README.md, you said that shadows didn't render correctly in IB and that it might be an IB bug.

I am using Xcode 7.3 beta and shadows are rendering just fine. Just thought I'd let you know.

**Comment by JakeLin** [comment]
I have tried this morning, and it still can't render correctly in IB. I will check it again once Apple release Xcode 7.3 GM and update README.md if it has been fixed. Thanks.

<img width="1216" alt="screen shot 2016-03-02 at 8 24 55 am" src="https://cloud.githubusercontent.com/assets/573856/13443658/251d02a2-e056-11e5-8cd8-fcc32675c48b.png">
