### ISSUE TITLE
Applying Gradient Crashes

### ISSUE THREAD

**Issue by rscodra** [IBAnimatable/IBAnimatable#120]
This is my first time trying this and i've tried adding a gradient and it's throwing these two errors:

Failed to update auto layout status: The agent raised a "CALayerInvalid" exception: layer <CAGradientLyaer : 0x7fc314889e50> is part of cycle in its layer tree

 Failed to render instance of AnimatableView: The agent threw an exception 

I've been tempering with it for quiet a while and couldn't find a solution. I added IBAnimatable through cocoapods.

The project is empty and has probably about 2-3 UIView's

**Comment by JakeLin** [comment]
@sambing thanks for reporting this, can you share your demo project? I am not able to reproduce this issue.

**Comment by tbaranes** [comment]
I think we fixed this crash in master but didn't release it. Could try to target the last version of master?

**Comment by rscodra** [comment]
So is it fixed? @tbaranes how would i do that?

**Comment by tbaranes** [comment]
Not sure if your case is releated, but we have a crash fixed related to the gradient including in the next version. 

What are you using to install `IBAnimatable`? If it's CocoaPods, just copy the following line to your podfile:

```
pod 'IBAnimatable', :git => 'https://github.com/JakeLin/IBanimatable.git'
```

**Comment by rscodra** [comment]
That fixed it. Thank you.

**Comment by JakeLin** [comment]
@tbaranes thanks for fixing this issue. Because We are about to release 2.0, I won't make 1.2.1 release now. Sorry for the inconvenience @sambing .

**Comment by jiggajoe** [comment]
Thanks for sharing this. I spent a few hours on trying to figure this one out. PS: Thanks Jake for a great library

**Comment by JakeLin** [comment]
Sorry, @jiggajoe will do more frequent releases after 2.0. Thanks.

**Comment by rscodra** [comment]
@JakeLin No problem, thank you for the great support and a amazing library, i've been using it regularly. I did notice this when adding UITableViewControllers and applying a gradient from the interface builder if i have the size set to say 4.7in, on larger screens the gradient is cut off and the background color shows.

**Comment by JakeLin** [comment]
@sambing interesting, will look at it.
