### ISSUE TITLE
Animation: scaleTo

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#121]
Just though we didn't have it, but it could be useful!

**Comment by JakeLin** [comment]
Cool, since we can support parameters now, can support more animations with parameters. `scaleTo` is useful.

**Comment by phimage** [comment]
I am interested with scaleTo animation but also scaleFrom or maybe scale/scaleFromTo

Using spring animation (animation with timing function could also be done)

# scaleTo(x, y) ( = scale(1, 1, x, y) )
```swift
        //view.transform = CGAffineTransform.identity
        UIView.animate(withDuration: configuration.duration,
                       delay: configuration.delay,
                       usingSpringWithDamping: configuration.damping,
                       initialSpringVelocity: configuration.velocity,
                       options: ...,
                       animations: {
                        self.view.transform = CGAffineTransform(scaleX: x, y: y) 
        }, completion: ...)
```
# scaleFrom(x, y)  ( =  scale(x, y, 1,1) )
```swift
        view.transform = CGAffineTransform(scaleX: x, y: y)
        UIView.animate(withDuration: configuration.duration,
                       delay: configuration.delay,
                       initialSpringVelocity: configuration.velocity,
                       options: ...,
                       animations: {
                        self.view.transform = CGAffineTransform.identity
        }, completion: ...)
```

# scale(fromX, fromY, toX, toY)
```swift
        view.transform = CGAffineTransform(scaleX: fromX, y: fromY)
        UIView.animate(withDuration: configuration.duration,
                       delay: configuration.delay,
                       initialSpringVelocity: configuration.velocity,
                       options: ...,
                       animations: {
                        self.view.transform = CGAffineTransform(scaleX: toX, y: toY)
        }, completion: ...)
```

If I could PR something about that after TimingFunctionType
if we choose the new `AnimationType` case

**Comment by JakeLin** [comment]
@phimage Since `IBAnimatble` has decent features for designing in Interface Builder. We can keep going with improving the animation programming APIs. How about we set the theme to animation programming APIs and UT improvements for release 5? Can you re-submit the timing function PR again? let's unblock it and keep going with the other great improvements like this one.
