### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by azxfire** [IBAnimatable/IBAnimatable#130]
func iterateEnum<T: Hashable>(_: T.Type) -> AnyGenerator<T> {
  var i = 0
  return AnyGenerator {
    let next = withUnsafePointer(&i) { UnsafePointer<T>($0).memory }
    let currentI = i
    i = i + 1
    return next.hashValue == currentI ? next : nil
  }
}
argument passed to call that takes no arguments?
result values in '?:'espression have mismatching type 'T' and '_'

**Comment by JakeLin** [comment]
Are you using Xcode 7.3? If yes, you should be able to build. If you are using Xcode 7.2, then please upgrade Xcode, or `git checkout 2.0` back to older version.  Or download the source code from https://github.com/JakeLin/IBAnimatable/releases/tag/2.0 

Please let me know if you have any questions.

**Comment by azxfire** [comment]
Thank you.I solved this.
