### ISSUE TITLE
Chain-able animations

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#14]
Better syntax for chaining animations.

Just an idea

```
Animation(view).pop(repeatCount: 2).then.shake(repeatCount:1).and.rotate(.cw, repeatCount:2)
```

**Comment by shshalom** [comment]
Hi @JakeLin, Is there any chance to push this to an earlier version?  that's my only blocker from using this great framework.

**Comment by JakeLin** [comment]
@shshalom  I don't have any plan to work on this feature yet. If you would like to take the initiative, please go head, I will offer some help if I can.

**Comment by shshalom** [comment]
I might do that :-).

I wonder, how should we go about this. did you had anything in mind? maybe follow some other similar library that does it?

**Comment by JakeLin** [comment]
@shshalom great, I don't have a concrete idea how can we do it, I think there are a few ways we can try.
1. Similar to https://github.com/Draveness/DKChainableAnimationKit 
   which provides nice syntax like `view.animation.makeScale(2.0).spring.animate(1.0)`, They provide an extension property called `animation` for all `UIView` objects in https://github.com/Draveness/DKChainableAnimationKit/blob/master/DKChainableAnimationKit/Classes/UIView%2BAnimationKit.swift#L15 . I don't think we need to do it as an extend method / property for `UIView` because we use protocol orientated programming pattern. It can be a property of `Animatable` protocol. They also used Objective-C black magic `objc_getAssociatedObject` because the library was ported from https://github.com/jhurray/JHChainableAnimations . I don't mind but we try to avoid it in `IBAnimatable` if possible.
2. Some Promise / Future support like https://github.com/mxcl/PromiseKit, https://github.com/Thomvis/BrightFutures, or https://github.com/FutureKit/FutureKit
   They provide comprehensive features to control the flow of animations. I think they are overkill for animation library like `IBAnimatable`.  I prefer to have a simple solution for both API usage and implementation. But their ideas can be reused in some place.
3. Something simple I don't know yet.

We don't need to make a decision right now, we can have some [spikes](http://agiledictionary.com/209/spike/) to try out different potential approaches. And make the decision once we get something. I think it will be a lot of fun😉 and a few of pains too.

**Comment by gkye** [comment]
https://github.com/AugustRush/Stellar is also a pretty good example

**Comment by shshalom** [comment]
@JakeLin Nice find, I'll get to it this weekend I hope.
I'll do some research and try to figure what would be the most simple and elegant approach.

 @gkye  Thanks for the link :-)

I'll post an update as soon I'll get some insights.

**Comment by tbaranes** [comment]
Closing in favor of #382
