### ISSUE TITLE
Doesn't work in latest xcode

### ISSUE THREAD

**Issue by pixelbendr** [IBAnimatable/IBAnimatable#142]
I have recently updated my Xcode and the library doesn't work in interface builder.

Sample Error

"IB Designables: Ignoring user defined runtime attribute for key path "maskType" on instance of "UIButton". Hit an exception when attempting to set its value: [<UIButton 0x7f946aeb9e50> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key maskType.
"

**Comment by tbaranes** [comment]
Did you update to Xcode 7.3? It's working well in the demo app. Could you share more information that could help? Setup of your `UIButton`? A sample project? A screenshots? Well, anything that you can share :innocent: 

Thanks!

**Comment by JakeLin** [comment]
@pixelbendr could you please provide more details as @tbaranes mentioned? 

Do you use CocoaPods, Carthage or SPM?
Did the project used to work before your upgrade to Xcode 7.3?
Which pod did you install? 1.2/2.0/2.1
Did you try to re-open Xcode?
Did you try to clear derived data?
Did you check Identity Inspector, make sure your Button is using `AnimatableButton`, Module field is good?

Please let me know if you have any questions? Thanks

**Comment by pixelbendr** [comment]
@JakeLin @tbaranes its working now. :) The only issue is when I copy and paste from the example project it doesn't work. I had to restart my Mac before it started working. Regards.
