### ISSUE TITLE
@IBOutlet weak var error

### ISSUE THREAD

**Issue by pixelbendr** [IBAnimatable/IBAnimatable#159]
Am not able to use IBOutlet, is this an Xcode issue?

Regards.

**Comment by JakeLin** [comment]
@pixelbendr can you provide more details? Which element did you try to use, `AnimatableView`, `AnimatableButton` or others? 

Can you specify the step you try to use `IBOutlet`? Ctrl+Drag? 

Can you specify the Xcode version?

Can you tell us the IBAnimatable version?

Can you tell us how do you use it, CocoaPods, Carthage?

**Comment by pixelbendr** [comment]
Which element did you try to use, AnimatableView, AnimatableButton or others?
**AnimatableView**

Can you specify the step you try to use IBOutlet? Ctrl+Drag?
**Dragging**

Can you specify the Xcode version?
**7.3**

Can you tell us the IBAnimatable version?
**1.2**

Can you tell us how do you use it, CocoaPods, Carthage?
**CocoaPods**

**Comment by tbaranes** [comment]
Did you `import IBAnimatable` in your file as well?
What is the exact error that you are getting?

**Comment by pixelbendr** [comment]
thats the problem, the import. Thank you. Regards.

**Comment by tbaranes** [comment]
You're welcome :tada:
