### ISSUE TITLE
Material design components

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#16]
Material design components like MaterialButton

Please see https://github.com/JakeLin/IBAnimatable-Material

**Comment by JakeLin** [comment]
Material Design Components: https://www.google.com/design/spec/components/bottom-sheets.html

**Comment by JakeLin** [comment]
an iOS implementation https://github.com/CosmicMind/Material

**Comment by damtsnkff** [comment]
How do you see this ? Re-creating all the components, or just support another implementation (like the one mentioned above) ?

**Comment by kodekarim** [comment]
this library will be one stop solution for iOS Developer to design and prototype.. great work @JakeLin Sir

**Comment by JakeLin** [comment]
@damtsnkff it will be a plugin of IBAnimatable and based on Material project. It should get all updates from both projects in the future. Because IBAnimatable uses protocol oriented programming paradigm , it's very easy to use it to extend the other UI libraries. 

We are moving the entire project to new organisation GitHub.com/IBAnimatable . This plugin will be a sub project of this organisation. Would you like to work on this Material Design project ? Please let me know if you're interested. We can work together to develop it and have fun together.

@abdulKarim002 glad you like it, it's great team effort especially to Tom.

**Comment by damtsnkff** [comment]
@JakeLin Interesting. When are you moving the project as a new organisation ? I don't know if my skills are enough but I'd definitely be interested in doing this. Doesn't seems that hard.

**Comment by JakeLin** [comment]
@damtsnkff We are doing that now as Release 2.5. Please see the discussion on https://github.com/JakeLin/IBAnimatable/issues/235

It is not hard. You can try and I always love to offer support if I can. How do you think?

**Comment by JakeLin** [comment]
![animatableraisedbutton](https://cloud.githubusercontent.com/assets/573856/16713775/151b34d6-46f5-11e6-9334-875453a01a9a.gif)

@damtsnkff I have started playing around this task and created `AnimatableRaisedButton`. I added you to the project https://github.com/JakeLin/IBAnimatable-Material , will move it to the IBAnimatable organisation once the main project moves to it.

**Comment by damtsnkff** [comment]
@JakeLin Ok perfect. Then I'll have a look on what you started.

**Comment by tbaranes** [comment]
Nice starter @JakeLin, that's looks very promising!

**Comment by tbaranes** [comment]
Closing this now since the [IBAnimatable-Material](https://github.com/JakeLin/IBAnimatable-Material) has its own development running!
