### ISSUE TITLE
Set Corners and Shadow of AnimatableView by Code

### ISSUE THREAD

**Issue by winkelsdorf** [IBAnimatable/IBAnimatable#172]
Hi,

what a great framework, speeds up my development cycle 👍 

Probably in contrary to the most, I use this by Code as I need a little more fine grain about the animation details depending on different adaptive size classes (device traits).

I noticed a bug: When setting rounded corners and shadow by code, the rounded corners are ignored. I know _why_ (`maskToBounds`, `clipToBounds`), but I am wondering if I can invoke your internal calls manually?

e.g. when using a UIPresentationController I do the following (stripped out unrelated stuff):

```
    override func presentationTransitionWillBegin() {
        dimmingView.frame = containerView?.bounds ?? CGRect.zero
        containerView?.addSubview(dimmingView)
        dimmingView.addSubview(presentedViewController.view)

        if let view = presentedViewController.view as? AnimatableView {
            view.cornerRadius = 20
            view.shadowColor = UIColor.blackColor()
            view.shadowRadius = 10
            view.shadowOpacity = 0.5
        }
      ...
  }
```

As said shadow is applied, corner ignored.

Next I am searching if you have any ready-to-use Pop animation as UIViewControllerAnimatedTransitioning which I can use in the above UIPresentationController in my own adaptive UIViewControllerTransitioningDelegate (returns different UIViewControllerAnimatedTransitioning depending on source trait)..

If you can point me towards the right direction, any help would be welcome :)

Cheers,
Frederik

**Comment by JakeLin** [comment]
@winkelsdorf thanks for reporting this, I need more time to investigate that, I did a quick try on IB, it is working fine, if you can share a demo project with just the problem bit, it will be faster.

<img width="662" alt="screen shot 2016-04-19 at 9 23 08 am" src="https://cloud.githubusercontent.com/assets/573856/14622898/bc87e7c6-0610-11e6-950c-d98ef8f431ea.png">

Did you set the `shadowOffset`?  Did you use any view inspector like RevealApp to find out the runtime attributes, especially for the corner? IF some one reset it, find out where and why?

We call `commonSetup()` in `ShadowDesignable` to set the `layer.masksToBounds`, can you toggle it and see, but it may not help the corner though.

**Comment by winkelsdorf** [comment]
Just wanted to let you know: I'll check back in a few days, currently busy with a release..

**Comment by tbaranes** [comment]
Don't know about your main issue, but I can help with the second question:

> if you have any ready-to-use Pop animation as UIViewControllerAnimatedTransitioning which I can use in the above UIPresentationController in my own adaptive UIViewControllerTransitioningDelegate (returns different UIViewControllerAnimatedTransitioning depending on source trait)..

We have to update our documentation about that part, but here a list of all the transitions ready to use we have:  [TransitionAnimationType](https://github.com/JakeLin/IBAnimatable/blob/master/IBAnimatable/TransitionAnimationType.swift). Not sure you will find a a _real pop animation_ but, who know?

In `IBAnimatable`, we abstract the usage for three cases, so I'm pretty sure that you can use them with your own use case, here some examples that can help you:
- [Custom segues transitions](https://github.com/JakeLin/IBAnimatable/blob/master/IBAnimatable/Presenter.swift)
- [Custom push / pop transitions](https://github.com/JakeLin/IBAnimatable/blob/master/IBAnimatable/Navigator.swift)
- [Custom Container (child view controller) transitions](https://github.com/JakeLin/IBAnimatable/blob/master/IBAnimatable/ContainerTransition.swift)

You can play with each animation in the demo project by clicking on `forgot password`.

**Comment by JakeLin** [comment]
We have a set of transition animators can be used in `UIPresentationController` but don't have a `Pop` animation. I think it is a common requirement to have animatable `UIPresentationController`, I am going to create a card for it and close this issue for now. 

@winkelsdorf if you have any question, or you'd like to provide more information, please let us know, thanks.
