### ISSUE TITLE
HELP: Is it possible to create a diagonal view using IBAnimatable? 

### ISSUE THREAD

**Issue by tokyoooo** [IBAnimatable/IBAnimatable#173]
Is it possible to create a view like the image shown below using IBAnimatable? (Could I use a mask or something similar on the UIView?)

![](http://i.stack.imgur.com/7KwZS.png)

**Comment by JakeLin** [comment]
@tokyoooo  Yes, We can design the app like that with IBAnimatable in IB, but we don't provide that kind of support for particular app design request, sorry, I close this issue now.
