### ISSUE TITLE
UITextField Right Image option is not showing Image ...!!

### ISSUE THREAD

**Issue by kodekarim** [IBAnimatable/IBAnimatable#176]
Hello sir,
UITextField left image is working properly but the right side image is not, i have attached the image file kindly have a review and lastly i would like to say it's a really great library to design...Great work 

Any Suggestion/help would be helpful .<br>
![group](https://cloud.githubusercontent.com/assets/13949425/14769151/1205a2de-0a70-11e6-868f-ded2e5b06c77.png)

**Comment by tbaranes** [comment]
Hey! Thanks for the report. I just push a PR to fix your issue. It will be available around tonight or tomorrow, just the time that @JakeLin review the PR.

👯

**Comment by kodekarim** [comment]
Thank you sir..
