### ISSUE TITLE
Issue with AnimatableTextField

### ISSUE THREAD

**Issue by jlgaustin** [IBAnimatable/IBAnimatable#179]
After I updated pod from 1.0.1 to latest 2.2 version, borderSide doesn't work for me any longer in IB.   If I set borderWidth to 1, borderColor to grey and borderSide to Bottom.   I get border on all 4 sides regardless.   If I revert back to 1.0.1 it works again.   Any ideas?

**Comment by JakeLin** [comment]
@jlgaustin thanks for reporting this, looking at this issue now.

**Comment by JakeLin** [comment]
@jlgaustin I did a try with your specified parameters, and it works fine

<img width="1050" alt="screen shot 2016-04-26 at 12 17 31 pm" src="https://cloud.githubusercontent.com/assets/573856/14804700/f8e78af8-0ba8-11e6-9831-d5450b5476fd.png">

Can you check "Border Style", it must be `borderStyle = .None`

<img width="638" alt="screen shot 2016-04-26 at 12 19 35 pm" src="https://cloud.githubusercontent.com/assets/573856/14804736/46f412de-0ba9-11e6-83ea-f27125370afa.png">

If it is not `.None`, it will look like this.

<img width="622" alt="screen shot 2016-04-26 at 12 20 06 pm" src="https://cloud.githubusercontent.com/assets/573856/14804739/4a8de3d4-0ba9-11e6-9627-c07d58306309.png">

Please let me know if it still doesn't work for you or you have any questions, thanks.
