### ISSUE TITLE
Hello Sir, how about adding a placeholder in UITextview ..!

### ISSUE THREAD

**Issue by kodekarim** [IBAnimatable/IBAnimatable#181]
This library got everything to get a push in development so sir if you like can you add a placeholder in UITextview, it can be added programmatically but if it is available in IBAnimatable which is a great library it would be great.

**Comment by JakeLin** [comment]
@abdulKarim002 Thanks for your suggestion, we need to prioritise this. BTW, could you like to give it a go? It will be in `public extension PlaceholderDesignable where Self: UITextView`. Please let me know if you have any questions.

Some resources:
https://github.com/devxoul/UITextView-Placeholder
http://stackoverflow.com/questions/1328638/placeholder-in-uitextview/1704469#1704469
https://github.com/cbowns/MPTextView/blob/master/MPTextView.m

**Comment by tbaranes** [comment]
Another that could be great is to make a floating option for the placeholder:
https://github.com/Skyscanner/SkyFloatingLabelTextField
https://github.com/jverdi/JVFloatLabeledTextField

**Comment by TheDarkCode** [comment]
@JakeLin I'll add this to my list for the week.
