### ISSUE TITLE
Support for latest version of swift

### ISSUE THREAD

**Issue by learnwithgabbar** [IBAnimatable/IBAnimatable#182]
Hello sir, this is one of the great library i am using in my project , it's help me to reduce my work load to create view and other UI stuff , but when we shifted our work to latest version of swift it starts giving warning to covert syntax .
Is there is any plan to upgrade it to swift 2.2

**Comment by JakeLin** [comment]
@techmehra , which version are you using? `IBAnimatable` is using Swift 2.2 since release 2.1, we did it as same day as Xcode 7.3 went live. The current release 2.2.

**Comment by JakeLin** [comment]
@techmehra please let me know if you still have problem with the Swift version, thanks.
