### ISSUE TITLE
How to stop/cancel an animation

### ISSUE THREAD

**Issue by klwoon** [IBAnimatable/IBAnimatable#183]
Hi, may I ask how to stop or cancel an ongoing animation? In my app I'm rotating an AnimatableImageView indefinitely, and need to stop the rotation when the user presses some other buttons.

Thank you.

**Comment by JakeLin** [comment]
@klwoon can you try `self.layer.removeAnimationForKey("rotate")`? It should be able to cancel the `rotate` animation.

**Comment by klwoon** [comment]
Thank you, it worked!
