### ISSUE TITLE
Reuse animators animations in Animatable

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#187]
In IBAnimatable, we write the `Fade` animation two times: in `Animatable`, and as an `Animator`. That one is small and easy to create from scratch, so it's not a big deal, but creating an explode between two `UIView` is really more annoying. Currently, we would have to create it back from scratch or copy and adapt the code from `ExplodeAnimator`.

Don't you think we could make the animators more generic to be used as a transition, but also in `Animatable`?

**Comment by JakeLin** [comment]
@tbaranes I don't have straight answer for this, it will be great to share the logic between `Animatable` in `***Animator`s. Maybe encapsulate some view logic out in https://github.com/JakeLin/IBAnimatable/blob/master/IBAnimatable/ExplodeAnimator.swift#L71 Need to do a spike to try out.

**Comment by tbaranes** [comment]
I played a bit with it to see how it could be done, from what I see it finally doesn't make sense to reuse them in Animatable. An animator needs two views to do a transition, Animatable works with only view by time, which means most of the animators are basically not compatible. If we need a NatGeo animation between two `UIView` that may means we have a conceptual issue.

Some of them could have bit refactored to be used this way like the Explode, it would have been easy to reuse it, but it's probably not worth it right now.

I'm closing this for now, and we can come back here if that become a real feature request.
