### ISSUE TITLE
Design transition animations in Interface Builder

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#19]
Not only system built-in transitions, more custom transitions support.
- [x] `AnimatableNavigationController` to support custom transition animations for Push and Pop
- [x] `AnimatableViewController` to support custom transition animations for Present and Dismiss
- [x] <del>`AnimatableTableViewController` to support custom transition animations for Present and Dismiss</del>
- [x] `Present***Segue` to support custom transition animations for Present and Dismiss
- [x] `***InteractiveAnimator` to support gesture to Pop or Dismiss VC. e.g. Pan, ScreenEdgePan and Pinch.
- [x] <del>More custom animations.</del>

**Comment by tbaranes** [comment]
Do you have any preferences about which transitions should be implemented or examples of the results expected?

**Comment by lexrus** [comment]
Some concepts:
https://github.com/entotsu/TKSubmitTransition
https://github.com/NewAmsterdamLabs/ZOZolaZoomTransition
https://github.com/AlvaroFranco/AFBlurSegue

I think image zooming segue is very useful in most Apps. And it's handy to dismiss it with swap like Jake said in #20 .

**Comment by tbaranes** [comment]
Other list of concepts: http://transitiontreasury.com

**Comment by lexrus** [comment]
https://dribbble.com/shots/2131325-Bike
https://dribbble.com/shots/1216761-Liquid-Animation

**Comment by JakeLin** [comment]
First thing, we need to setup an architecture for that. I got three ideas to achieve that. 
1. An animator conforms to `UIViewControllerAnimatedTransitioning` and drag `NSObject` into a `UINavigationController` on IB (on top of the Controller), set that `NSObject` to that animator, set that navigation controller's delegate to it. Then all transitions within that navigation controller will use the animation specified in that animator.
2. Add two properties into `AnimatableViewController` like `transitOutAnimation` and `transitInAnimation`, let `AnimatableViewController` conform to `UIViewControllerAnimatedTransitioning` and pick up the animation according to those two properties.
3. Subclass `UISegue` for different transition animations. e.g. `FadeInOutPushSegue` for fade in when push and fade out when pop. `FadeInOutPresentSegue` for fade in when present and fade out when dismiss.

I am not sure will they work or not, need to create spike for them, I prefer the option 3 because when the user connect the segue they can select the predefined transition for the segue. 

When we have this architecture, we can refer to a lot of nice implementation on Github to add them on bit by bit. 

Those two as I mention in the roadmap  https://github.com/ColinEberhardt/VCTransitionsLibrary and http://transitiontreasury.com/ I would like to start with. You guys ones are all very good as well.

Any feedback is welcome. And I go lunch, very hungry 🍚

**Comment by tbaranes** [comment]
I definitely prefer the option 3. Seems to be the easiest to use: just set a custom segue, and you are done. 

Should we also think about a way to use them programatically? The disadvantage of option 3 is that we can't use it outside of a storyboard.

**Comment by JakeLin** [comment]
@tbaranes , @lexrus Please have a look at #110 when you have time, I have added a checklist above for this story. I am working on `AnimatableViewController` and `AnimatableTableViewController` at that moment. Please let me know if you have any questions, thanks.

@tbaranes to support custom animations programmatically, we can provide a set of custom Animators, you can find them in #110 as the example. The users can still use the way Apple provides for custom transitions, or just use our `AnimatableNavigationController` or `Push**Segue` in IB.

**Comment by JakeLin** [comment]
I have removed "`Push***Segue` to support custom transition animations for Push and Pop" because the transition animation should be consistent in the same `NavigationController`. And we already support the custom transition in `AnimatableNavigationController`.

And also added "`***InteractiveAnimator` to support gesture to Pop or Dismiss VC. e.g. Pan, ScreenEdgePan and Pinch." item.

**Comment by tbaranes** [comment]
Awesome work @JakeLin :+1:

**Comment by JakeLin** [comment]
Release 2.0 is out first. More transition tasks are in

[More interactive animators/controllers](https://github.com/JakeLin/IBAnimatable/issues/125)
[More transition animators/animation controllers](https://github.com/JakeLin/IBAnimatable/issues/126)
