### ISSUE TITLE
AnimatablePresentationController

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#198]
`AnimatablePresentationController` can support the user in prototyping and designing Modal View ( `UIPresentationController`) in Interface Build. 

It may have the following properties.
- [x] `cornerRadius`, `shadowColor`, `shadowRadius`, `shadowOpacity`, etc. for the Modal View, most of properties are supported by `AnimatableView` 
- [x] `dimmingViewBackgroundColor`, `dimmingViewOpacity`, `dimmingViewBlurEffect`, etc for background dimming view
- [x] `animationType`, e.g. `Pop(direction)` and all supported transition animators
- [x] `dismissGestureType`, e.g. `Swipe`, `Tap`
- [x] Custom size / position
- [x] `observeKeyboard`, up the modal when keyboard is opening
- [ ] `useDynamics`, use UIKit Dynamics when panning the view
- [x] `OverCurrentContext`  / fullscreen

Just some initial idea, feedback is welcome. Don't know which Milestone will work on it, so put "help wanted" 😉

Relative to #172, #281 and #20

**Comment by tbaranes** [comment]
There's definitely some ideas to take from [MZFormSheetPresentationController](https://github.com/m1entus/MZFormSheetPresentationController).

For the milestone, why not add it to the 2.4, or 4.0 if we don't have a 2.4?

**Comment by JakeLin** [comment]
@tbaranes I tag it to 4.0, but can be done earlier if needed.

**Comment by TheDarkCode** [comment]
@JakeLin I might take this on - in some part - during the upcoming week, depending on time. Would be a really cool feature to have.

**Comment by JakeLin** [comment]
Thanks guys, should we swap 4.0 with 3.0? I don't have many ideas on the goal of Sketch plugin. If yes, we can just change the number in the milestone.

**Comment by tbaranes** [comment]
I think so, we can still move on the plugins once we determine a clear roadmap for them.

**Comment by JakeLin** [comment]
@tbaranes I have swapped 3.0 and 4.0. Let's don't worry about Sketch plugin first.

**Comment by tbaranes** [comment]
I'd like to add more examples to cover all the features supported by our presentation controller. Which one should be the best:
- A list containing different ready use cases (like the current transition examples): animations, custom dimming view, ... we can easily create at least 20 examples using a list
- Creating a list of textfield for each customisation available, and creating the popup based on the values entered by the user

Any preferences?

**Comment by JakeLin** [comment]
I like the examples what @lastMove did for other features, how about we have a list of fields to let the user select
- animationType (picker view) 
- modalPosition (picker view)
- modalSize (picker view)
- cornerRadius (slider)
- dismissOnTap (toggle)
- backgroundColor (don't know how to present this, color picker or hex code)
- opacity (slider)
- blurEffectStyle  (picker view)
- blurOpacity  (slider)
- shadowColor (the UI is same as backgroundColor)
- shadowOpacity (slider)
- shadowRadius (slider)
- shadowOffset (two silders?)

Just an idea, feel free to make any feedback 😊

**Comment by JakeLin** [comment]
@tbaranes shall we close this issue now since we have a powerful [AnimatablePresentationController](https://github.com/IBAnimatable/IBAnimatable/blob/master/IBAnimatable/AnimatablePresentationController.swift). We can create another card if we need to work on other features. Some of the features are original thoughts.

**Comment by tbaranes** [comment]
There just one more featureI that I think is important enough: `OverCurrentContext / fullscreen` implemented, otherwise, can close it if you want :)

**Comment by JakeLin** [comment]
@tbaranes thanks, either we close this one can create a new one for `OverCurrentContext / fullscreen` or leave this one. 

I think we can leave this one for now.

**Comment by kodekarim** [comment]
PresentationModalSize - custom size is not working.. kindly have a look
Half and full parameters are working but the custom size is not..

**Comment by tbaranes** [comment]
@abdulKarim002 Can you open a new issue about this including as much details as you have?

**Comment by kodekarim** [comment]
Yes sure...
