### ISSUE TITLE
Invisible IBInspectable properties

### ISSUE THREAD

**Issue by lexrus** [IBAnimatable/IBAnimatable#203]
IBInspectable properties are invisible while IBAnimatable was installed with Carthage.

Check out: https://github.com/Carthage/Carthage/issues/335

Since IBInspectable is widely used in IBAnimatable, we should annotate this issue in the README.

**Comment by JakeLin** [comment]
@lexrus Thank you for letting me know, I am curious it works on the framework built from source code like what we are doing for the Demo app but not from Carthage.

I close it now since I have updated the README.md.
