### ISSUE TITLE
Parallelogram Mask support in Maskdesignable

### ISSUE THREAD

**Issue by lastMove** [IBAnimatable/IBAnimatable#205]
Hi, 

Thanks for this amazing library. 
It’s the way to go. 

I have an improvement for MaskDesgignable.

I have just added support for parallelograms To MaskDesignable. 

Usage : 
Parallelogram(angle)

Parallelogram(90) give a rectangle. 

for angle < 90 It gives a left oriented Parallelogram and for angle > 90 it gives a right oriented Parallelogram. 

I will make a PR Soon. 
I didn’t see this in your vision / roadmap. 

Will you accept this PR ? 

(Sorry for my english, I am French :) )

Jason.

**Comment by tbaranes** [comment]
PR are very welcomes even if it's not in our roadmap / vision! New features are always welcome if it's respect the vision of IBAnimatable. We will review it once submit 👍
