### ISSUE TITLE
Document how to use git submodule

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#22]

**Comment by lexrus** [comment]
Do you prefer the tr;dr version:
https://github.com/alamofire/alamofire#embedded-framework
Or the ask Google version?
https://github.com/thoughtbot/Argo#git-submodules

**Comment by tbaranes** [comment]
I think that should follow as much as possible the same description as the CocoaPods, Carthage... only the strict necessary. If we want to do the tr;dr, we should do it for each sort of installation.

**Comment by JakeLin** [comment]
Thanks @lexrus I took the ask Google version. If the user wants to use git submodules, should be able to do it by themselves.
