### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#221]
Discuss the topics for Swift 3 support. We are working on [swift3 branch](https://github.com/JakeLin/IBAnimatable/tree/swift3) to support Swift 3. Once Xcode 8 RTM, we merge it to master.
- [x] Fix all build errors #222
- [x] Improve all enums #218 
- [x] More Swifty APIs
- [x] Update playground

Some remain works need to be done
- [x] BorderSide in the demo doesn't work
- [x] Blur effect in playground app doesn't work - It doesn't change when we change "Blur"
- [x] Predefined gradients in playground app doesn't work 
- [x] Gradients in playground app doesn't work 
- [x] Mask option "None" in playground app doesn't work 
- [x] Transition in playground app crashes
- [x] Container Transition in playground app doesn't work 
- [x] Fix all purple colors
- [x] Presentation transition doesn't work
- [x] Upgrade activity indicators
- [x] Fix all factor methods with `make***`
- [x] Fix all methods from `config***` to `configure***`
- [x] Fix all `unwrapped***` variable.
- [x] Remove `repeatCount` in `Animatable`

**Comment by cemolcay** [comment]
can you update xcode 8beta6 please?

**Comment by JakeLin** [comment]
@lastmove has taken the initiative on this, please have a look at https://github.com/IBAnimatable/IBAnimatable/commit/22475b3911ef6b11938ecac58fb21f19442a957b

If you have time, could you please help us to check the changes? we also discuss a big change about access scope on #285

**Comment by vincentlong889** [comment]
Swift 3.0 Released!

**Comment by learnwithgabbar** [comment]
Not getting updated code on 2.8.1 
I updated code through pod but not getting the updated code, It giving error in every file

**Comment by tbaranes** [comment]
v2.8.1 is swift 2.3 support, if you want swift 3, you have to target the master directly, the swift 3 release will arrive this week or next one.

**Comment by learnwithgabbar** [comment]
Okay

**Comment by JakeLin** [comment]
Finally, we close this now, well done guys.
