### ISSUE TITLE
I couldn't build IBAnimatable Framework

### ISSUE THREAD

**Issue by shiratsu** [IBAnimatable/IBAnimatable#226]
I would like to use this framework.
At first,I tried to test this project's example.
But I couldn't build.
There are so many errors.

![2016-06-23 14 19 55](https://cloud.githubusercontent.com/assets/918490/16292559/a58c6324-394d-11e6-85a9-33da80287239.png)

How do i resolve?
This error says the name of variable is too short to define.

**Comment by JakeLin** [comment]
Hi, 

Can you check are you using Xcode 7.3？ if you use Xcode 8, pleas check out swift3 branch.

Thanks
Jake

**Comment by shiratsu** [comment]
I'm using Xcode 7.3.
But i already have Xcode8.
![2016-06-23 15 37 05](https://cloud.githubusercontent.com/assets/918490/16293926/63aa2c7e-3958-11e6-8bc4-dcd6217c9e05.png)
Does having both xcode7 and 8 cause above error?

**Comment by tbaranes** [comment]
Your errors are from `SwiftLint`, not the framework itself. Are you using the lastest version of SwiftLint?
Otherwise, you can disable `SwiftLint` script in xcodeproj if you just want to test quickly.

**Comment by shiratsu** [comment]
Year,I just realized SwiftLint.Thank you!
