### ISSUE TITLE
Moving to an organization

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#235]
Following the discussion in #104, I start to move IBAnimatable to an organisation, but there still few steps to do (I steal it from [Moya issue](https://github.com/Moya/Moya/issues/168)):
- [x] Create a new org: https://github.com/IBAnimatable
- [x] Add IBAnimatable contributors to the org
- [x] [Transfer the repo](https://help.github.com/articles/transferring-a-repository/) (and its related the org)
- [ ] Send a PR to [CocoaPods/Specs](https://github.com/CocoaPods/Specs) to change the git URLs to the new endpoint
- [x] Change all copyright info to IBAnimatable
- [ ] [Pull requests template](https://github.com/blog/2111-issue-and-pull-request-templates)
- [x] Invite all collaborators to the Slack channel. 

Not sure, but can be useful following where IBAnimatable is going:
- Create an org [code of conduct](http://contributor-covenant.org/version/1/2/0/).

**Projects to move**
- [x] https://github.com/JakeLin/IBAnimatable
- [x] https://github.com/JakeLin/IBAnimatable-Material
- [x] https://github.com/JakeLin/IBAnimatable-Misc
- [x] https://github.com/JakeLin/IBAnimatable-PackageManagementExamples
- [x] https://github.com/JakeLin/ibanimatable.com

If anyone has knowledge about others important steps, let's edit this todo list 👯

**Comment by TheDarkCode** [comment]
Code of conduct is probably the least-read document type on github. The main thing is getting contribution agreements so that the copyright is owned by the organization regardless of contributor.

**Comment by damtsnkff** [comment]
For the code of conduct, there is [this template](http://todogroup.org/opencodeofconduct/), used [here](https://code.facebook.com/pages/876921332402685/open-source-code-of-conduct) by Facebook and others.

**Comment by tbaranes** [comment]
Another thing we could add is [Pull requests template](https://github.com/blog/2111-issue-and-pull-request-templates). For each PRs (exceptions apart), their always some mandatory steps:
- Docs (README / API) update
- CHANGELOG updates
- Example app update
- ...

That will help to ensure we never forget one important step when submitting a new PRs. It's in the same idea as the [release a new version](https://github.com/JakeLin/IBAnimatable/wiki/How-to-release-a-new-version) documentation.

**Comment by JakeLin** [comment]
Cool, good ideas

**Comment by lastMove** [comment]
Nice ! (party) 
🎈 🎉  
New home ^^

**Comment by JakeLin** [comment]
Dear all, @TheDarkCode @damtsnkff @lastMove @gkye @lexrus Do you use Slack? Please send your email address to me (you can find my email at https://github.com/JakeLin), then we can send you an invite to IBAnimatable channel. Happy coding. 🎉

**Comment by JakeLin** [comment]
Have tested CocoaPods and Carthage, both are working fine with the new release 2.6 (with new organization) https://github.com/IBAnimatable/IBAnimatable-PackageManagementExamples

Time to bed 😴

**Comment by tbaranes** [comment]
Closing this since the migration is done. Still missing the PR template, but if that's really important, it will go up later.

**Comment by JakeLin** [comment]
Cool, thanks for organising this. 🎉
