### ISSUE TITLE
Upgrade Swift Playground to support Xcode 8

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#240]
For some reasons, the Swift Playground doesn't work anymore 😢 even for beta 2.

Relate to #221

**Comment by lastMove** [comment]
Strangely It's still not working on my side. There is no errors but nothing is shown. Anyone Else has this issue ? (Swift3 branch, Xcode 8 Beta 2)

**Comment by JakeLin** [comment]
@lastMove, My one (Version 8.0 beta 2 (8S162m) is still working. Did you try "Cmd + k" to clean and rebuild, I fixed them by commenting out all and uncommenting one line be one line to check. Xcode 8 beta is very fragile and can't display the error.
