### ISSUE TITLE
TransitionType UIViewController -> presentViewController

### ISSUE THREAD

**Issue by DonBaronFactory** [IBAnimatable/IBAnimatable#242]
Not sure what I do wrong but the transition does not seem to be applied... it still transitions with the standard built in transition... 

```
let vc = self.storyboard!.instantiateViewControllerWithIdentifier("view1") as! testViewController
vc.transitionAnimationType = "Fade(In)"
vc.transitionDuration = 2.0
self.presentViewController(vc, animated: true, completion: nil)
```

My UIViewController is a Subclass of AnimatableViewController ... 

any help?

**Comment by JakeLin** [comment]
@cre8it 

Why don't you use it in Interface Builder and segue? It is the simplest way to use the library.

And if you use in code. The `transitionAnimationType` is applied to fromViewController / sourceViewController, in your case is `self`.

Also, if you use in code, we recommend you using Apple's way like 

```
func animationControllerForPresentedController(presented: UIViewController, presentingController presenting: UIViewController, sourceController source: UIViewController) -> UIViewControllerAnimatedTransitioning? {
  return FadeAnimator()
}
```

It gives you full controll. Please let me know if you have any questions, thanks.

**Comment by DonBaronFactory** [comment]
Was late night, how can I miss this one... done it hundreds of time this way for custom transitions, but did not think of it when trying with IBAnimatable... Thank you for this awesome library which is in use in almost all my apps

**Comment by JakeLin** [comment]
@cre8it cool, one design principle of IBAnimatable is to extend but not change Apple's APIs. Please let me know if you have any questions. I close it now, but feel free to re-open if you have any questions.
