### ISSUE TITLE
UIVibrancyEffect designable?

### ISSUE THREAD

**Issue by f1nality** [IBAnimatable/IBAnimatable#243]
Hello! 
IBAnimatable has UIBlurEffect support, but doesn't have UIVibrancyEffect.
Can this be added?

Thanks!

**Comment by JakeLin** [comment]
@f1nality thanks for suggesting this feature, i think it is a good idea to have it. But when can we do it, I need to have a look first. Would you like to help us with that? We should be able to support you to do that.

**Comment by f1nality** [comment]
@JakeLin this feature is already being implemented by @tbaranes
