### ISSUE TITLE
Fix geometryFlipped

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#25]

**Comment by JakeLin** [comment]
To let IB render the shadow more correctly, currently, in IB renders opposite of actual device. we may need to handle `geometryFlipped`, but I have tried and it didn't work.

**Comment by TheDarkCode** [comment]
Is this still an issue, @JakeLin?

**Comment by JakeLin** [comment]
@TheDarkCode yes, will try again after WWDC to see if they fix it.

**Comment by JakeLin** [comment]
That has been fixed in Xcode 8 🎉
