### ISSUE TITLE
Losing AutoLayout constraints when using`blurEffectStyle` in a container view

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#255]
AutoLayout constraints will be gone when using`blurEffectStyle` in a container view.

![simulator screen shot jul 21 2016 7 02 02 pm](https://cloud.githubusercontent.com/assets/573856/17017175/a6e405fe-4f75-11e6-9be8-489ea8f2f915.png)

May document it and remove `BlurDesignable` from `AnimatableScrollView` and `AnimatableStackView`

**Comment by tbaranes** [comment]
Instead of removing from `AnimatableScrollView` and `AnimatableStackView`, can't we _transfer_ the constraints to the new view?

**Comment by JakeLin** [comment]
I'll try, but seems quite hard

**Comment by lastMove** [comment]
There is maybe another bug :  
Each time `configBlurEffectStyle` is called (when changing blurOpacity or blurEffect value for instance) a new Blur subview is added : `insertSubview(blurEffectView, at: 0)`. 
This behaviour can easily be tested using https://github.com/IBAnimatable/IBAnimatable/tree/feature/BlurEffectStyle

**Comment by tbaranes** [comment]
You are right @lastMove, we have to remove the previous one before adding a new blur view.

**Comment by JakeLin** [comment]
How about we add a tag like `IBAimatableBlurEffectView`? Then we can remove the effect view before re-add if it exists.

**Comment by tbaranes** [comment]
Sounds faire enough 👍

**Comment by lastMove** [comment]
You are thinking about a tag or about a UIView subclass. 
I prefer the internal subclass approach, since with tag there is a collision risk.

**Comment by JakeLin** [comment]
An internal or even private subclass would be better, I didn't figure out this approach, 👍

Jake

**Comment by tbaranes** [comment]
@JakeLin Did you find a solution about this issue? Should we update the docs? 
Another though, it could be great to add an example of blur / vibrancy in the playground app.

**Comment by lastMove** [comment]
I added a demo of blur / vibrancy "User interface => Blur Effect"
With your fix, it should work perfectly

**Comment by JakeLin** [comment]
@tbaranes I didn't find a solution for that, I think we should remove `BlurDesignable` from `AnimatableScrollView` and `AnimatableStackView`. And only `AnimatableView` and `AnimatableImageView` can support `BlurDesignable`. And add documentation comment to `BlurDesignable.vibrancyEffectStyle` to let the user know all constraints for the subviews will be lost once well apply the Vibrancy Effect style. The workaround is to reset the constraints programmatically.
