### ISSUE TITLE
import IBAnimatable error in playground

### ISSUE THREAD

**Issue by TifaTsubasa** [IBAnimatable/IBAnimatable#26]
import IBAnimatable is a error when I open IBAnimatable.playground, how do I start it

**Comment by alecsechechel** [comment]
+

**Comment by JakeLin** [comment]
@alecsechechel What issue are you having? do you use `IBAnimatable` in another project? you need to follow the doc from Apple https://developer.apple.com/library/ios/recipes/Playground_Help/Chapters/ImportFramework.html 

Another easier way to play around the playground is download the project and add new pages to the existing playground.

**Comment by alecsechechel** [comment]
@JakeLin Thanks it is work. I added playgrounds in projects. 
Cool thing!
