### ISSUE TITLE
Code is breaking on xcode 8.0 beta 4 

### ISSUE THREAD

**Issue by learnwithgabbar** [IBAnimatable/IBAnimatable#263]
Code is not working on xcode 8.0 beta 4, throws many error

**Comment by JakeLin** [comment]
@techmehra did you try swift3 branch https://github.com/IBAnimatable/IBAnimatable/tree/swift3

**Comment by learnwithgabbar** [comment]
Yes I have try the swift3 branch but throwing lot of error
and is there is any way to integrate it through cocoapods

**Comment by learnwithgabbar** [comment]
@JakeLin this library become one of my toolkit for ios development please help me with this

**Comment by JakeLin** [comment]
I need to upgrade it to support Xcode 8 beta 4, or can you help me with this to create a PR?

**Comment by learnwithgabbar** [comment]
@JakeLin    guard let unwrappedAnimationTypeString = animationType, animationType = AnimationType(rawValue: unwrappedAnimationTypeString) else {
      return
    }
getting use of local variable animationType before it declaration

**Comment by learnwithgabbar** [comment]
Type 'ContainerTransition' does not conform to protocol 'UIViewControllerContextTransitioning'

**Comment by learnwithgabbar** [comment]
Method does not override any method from its superclass  for frameOfPresentedViewInContainerView

**Comment by learnwithgabbar** [comment]
@JakeLin  i am not able to fix the  guard let unwrappedAnimationTypeString = animationType, animationType = AnimationType(rawValue: unwrappedAnimationTypeString) else {
return
} and now the code is working but animation is not working

**Comment by learnwithgabbar** [comment]
@JakeLin I have fixed the code for xcode 8.0 beta 4 please check the pull request

**Comment by Clcanny** [comment]
I meet the same problem in another framework, can you tell me how to fix it by myself?

**Comment by JakeLin** [comment]
@Clcanny Could you please put more details on what are you talking about? We support Xcode Version 8.2.1 (8C1002) already.
