### ISSUE TITLE
UIView has no corner radius when applied with a gradient

### ISSUE THREAD

**Issue by ingeniousgenius** [IBAnimatable/IBAnimatable#265]
I pretty much explained it in the title, Anyways I installed the latest version via Cocoapods and I need it urgently to continue my project :)

Here're some images showing it. It appears the corner radius mask does not apply to the gradients. In your tutorial, you manage to achieve what I am trying to do but for some reason, I 
 fail to replicate it.

Without Gradient - Corner Radius is there
![screen shot 2016-08-04 at 13 34 32](https://cloud.githubusercontent.com/assets/6454286/17401941/691fe3a4-5a48-11e6-9e66-c80c88984ea8.png)

With Gradient - It's gone
![screen shot 2016-08-04 at 13 34 41](https://cloud.githubusercontent.com/assets/6454286/17401940/691f1a32-5a48-11e6-9772-aa0b1ed0445d.png)

But if I have one of the colours in the gradient to alpha, you can see it covers the corner radius. How can I fix this?
![screen shot 2016-08-04 at 13 37 12](https://cloud.githubusercontent.com/assets/6454286/17401984/a3022262-5a48-11e6-868c-8469c49dddc0.png)

**Comment by tbaranes** [comment]
Thanks for reporting this, there was an issue in the gradient implementation, the `cornerRadius` was just ignored when a gradient was applied.

The PR #266 will fix your issue, once that's merged, you can target `IBAnimatable` master in your `Podfile` or wait for the next release.

**Comment by ingeniousgenius** [comment]
Thanks so much! I'll go ahead and add the changes manually :) Thanks for responding so quickly. I suspected it was something like that

**Comment by tbaranes** [comment]
🎉 Hope that was the right fix!
