### ISSUE TITLE
Shadows not working with Mask type.

### ISSUE THREAD

**Issue by Abdul-Moiz** [IBAnimatable/IBAnimatable#267]
I am trying to apply shadow on Mask type Circle seems like it's not working. Removing mask working properly.

**Comment by JakeLin** [comment]
@Abdul-Moiz I introduced this bug when I fixed another bug https://github.com/IBAnimatable/IBAnimatable/pull/180 , I am looking at how can we fix it.

**Comment by JakeLin** [comment]
@Abdul-Moiz  I have tried to fix this issue, please have a look at the commit https://github.com/IBAnimatable/IBAnimatable/commit/3c5bc85a9d6a7497ac58d64d9de2e8a75cbe810d

But the effect is not right, it is not easy to fix it. If you have time, can you have a look and let me know if you find anything? Thanks

![simulator screen shot aug 5 2016 11 45 48 pm](https://cloud.githubusercontent.com/assets/573856/17438717/aaa24f72-5b67-11e6-84ac-9a8a3917407f.png)

If you want to apply a shadow to a Circle, there is a workaround, you can set `cornerRadius = width / 2`.

**Comment by Abdul-Moiz** [comment]
@JakeLin I tried to look into the issue. Somehow the shadow is clipping within the view bounds. 
The approach I can think of to fix it is adding sublayer below main layer. And avoid the masking completely. 

For time being going with the workaround 2.

**Comment by JakeLin** [comment]
@Abdul-Moiz thanks for looking at it. As you said, I think we need to have two layers. And apply the mask to `shadowPath` of the second layer. Would you like to give it a go with a PR when you have time?  Please let me know if you are interested.

**Comment by Abdul-Moiz** [comment]
@JakeLin This is the code that made the shadow render correctly on the view with masking. I didn't tested all the cases but working fine for AnimatableView, Button and image.

```
public func configMaskShadow() {
    commonSetup()
    // if a layer mask is specified, display the shadow to match the mask
    if let mask = layer.mask as? CAShapeLayer {
      // Clear default layer borders
      layer.shadowColor = nil
      layer.shadowRadius = 0
      layer.shadowOpacity = 0

      // Remove any previous layer
      layer.superlayer?.sublayers?.filter { $0.name == "shadowLayer-\(unsafeAddressOf(self))" }
        .forEach { $0.removeFromSuperlayer() }

      // Create new layer with object's memory reference to make this string unique. Otherwise common name will remove all the shadow layers as it's adding in layer's superview.
      let shadowLayer = CAShapeLayer()
      shadowLayer.name = "shadowLayer-\(unsafeAddressOf(self))"
      shadowLayer.frame = frame

      // Configure shadow properties
      if let unwrappedShadowColor = shadowColor {
        shadowLayer.shadowColor = unwrappedShadowColor.CGColor
      }
      if !shadowRadius.isNaN && shadowRadius > 0 {
        shadowLayer.shadowRadius = shadowRadius
      }
      if !shadowOpacity.isNaN && shadowOpacity >= 0 && shadowOpacity <= 1 {
        shadowLayer.shadowOpacity = Float(shadowOpacity)
      }
      if !shadowOffset.x.isNaN {
        shadowLayer.shadowOffset.width = shadowOffset.x
      }
      if !shadowOffset.y.isNaN {
        shadowLayer.shadowOffset.height = shadowOffset.y
      }
      shadowLayer.shadowPath = mask.path

      // Add to layer's superview in order to render shadow otherwise it will clip out due to mask layer.
      layer.superlayer?.insertSublayer(shadowLayer, below: layer)
    }
  }
```

![simulator screen shot aug 11 2016 3 47 04 pm](https://cloud.githubusercontent.com/assets/3176559/17602697/c8cc1302-5fdb-11e6-8746-9ef756eb6cb3.png)

**Comment by JakeLin** [comment]
@Abdul-Moiz thanks, looks very good. The solution should be fine. I am busy on preparing a presentation for [Dev World](http://2016.devworld.com.au/)  will have a deep look later.

**Comment by JakeLin** [comment]
@Abdul-Moiz Sorry for the late action, I have submitted a PR #295  to address this issue, please have a look when you have time. Thanks for fixing this issue.
