### ISSUE TITLE
Flip issue

### ISSUE THREAD

**Issue by NiteshKhandal** [IBAnimatable/IBAnimatable#271]
when i tap on create Account then according to you next controller should open with flip animation but in the github it is opening with only with transition effect. please resolve it because i want flip animation between two UIViewController as soon as possible.

**Comment by tbaranes** [comment]
I just verify the demo app, there's no flip animation expected when clicking on `Creating account`. Where did you find that?

The flip animation is already available, you can find the demo by clicking on `Forgot Password` -> `Transitions` -> `Flip`. 
You can also find the documentation for custom transition [here](https://github.com/IBAnimatable/IBAnimatable/blob/master/Documentation/Transitions.md).

**Comment by JakeLin** [comment]
@NiteshKhandal I close this issue now, please let me know if you have any questions. Feel free to reopen it if you think there is an issue.
