### ISSUE TITLE
Update scripts to generate ColorType.swift and GradientType.swift

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#274]
Update `FlatColorsTypeScript.swift` and `GradientsTypeScript.swift` to generate `ColorType.swift` and `GradientType.swift`. 
- [x] `GradientsTypeScript.swift`
- [x] `FlatColorsTypeScript.swift`

We can generate the code using `#colorLiteral` like `#colorLiteral(red: 0.08235294118, green: 0.6980392157, blue: 0.5411764706, alpha: 1)`, then Xcode 8 can display the color in code editor like

<img width="1112" alt="screen shot 2016-06-27 at 1 41 17 pm" src="https://cloud.githubusercontent.com/assets/573856/16367989/c6c96920-3c6c-11e6-99b7-f2557c011bd6.png">

**Comment by gkye** [comment]
I've got a working script for `GradientsType` but i think it could be improved slightly. Any ideas? @tbaranes @lastMove 

https://gist.github.com/gkye/1bdc8ccf86099b26f6ef7204c487cfa7

**Comment by JakeLin** [comment]
@gkye LGTM, just a few of small suggestions about the method names.

`func getColorLiteral(hexString: String) -> String`
`func JSON(from urlToRequest: String) -> Data`
 `func parse(JSONData: Data) -> [[String: AnyObject]]?`

 I am not good at naming as well 😁, any feedback is welcome.
