### ISSUE TITLE
[Swift 3] Open VS Public 

### ISSUE THREAD

**Issue by lastMove** [IBAnimatable/IBAnimatable#285]
The highly discussed [Proposal 0117](https://github.com/apple/swift-evolution/blob/master/proposals/0117-non-public-subclassable-by-default.md) is now implemented : 

> Classes declared as public can no longer be subclassed outside of their defining module, and methods declared as public can no longer be overridden outside of their defining module. To allow a class to be externally subclassed or a method to be externally overridden, declare them as open, which is a new access level beyond public.  

We now have to choose
We have to explicitly decide which class are subclassable and which methods / properties are overridable. 
I am not a big fan of this decision to make classes non-subclassable by default, since we sometimes need to inherit from a class that was not designed for subclassing (for instance `UITabbar` etc). 
So I will not be very objective about this ;)

What do you think ?

**Comment by JakeLin** [comment]
@lastMove Thanks for picking up this.

`IBAnimatable` is an extension of `UIKit`. All `UIKit` elements will be `open`, I think `IBAnimatable` elements should be `open` too. Even our demo also subclasses from some `IBAnimatable` elements. So I prefer to use `open` for all `IBAnimatable` UI classes.

But I think it is almost not to subclass transition animators. We may keep them `public`

**Comment by tbaranes** [comment]
> Personnaly I would prefer to let the biggest part of the Framework open. And use public only when the classes/methods/properties are dangerous to subclass or override. (Sometimes I found myself subclassing class that was not intended for. To fix some behaviours)

_@lastMove comments from #287_ 

Just a question about this, shouldn't we do the reverse? Let `public` for the one we think that won't overridable then changing them to `open` if there good reasons. If it's for a bug, we should fix it. After, since the most of `IBAnimatable` elements are from `UIKit`, I agree with you to say they should be `open`.

**Comment by JakeLin** [comment]
@tbaranes I think we only set UI elements to `open` now. We may revisit them again since from `open` to `public` is a breaking change. And from `public` to `open` is a feature 😁
