### ISSUE TITLE
Xcode 8 Beta 6 IterateEnum

### ISSUE THREAD

**Issue by lastMove** [IBAnimatable/IBAnimatable#286]
Hi, 
Within the project there is a function that allows us to iterate over all values of an Enum (by returning an iterator). 
There is some change with UnsafePointer in the last beta release of Xcode 8 ; so the function don't compile anymore. 

``` Swift

public func iterateEnum<T: Hashable>(from: T.Type) -> AnyIterator<T>? {
var x = 0
  return AnyIterator {
    let next = withUnsafePointer(&x) {
      UnsafePointer<T>($0).pointee
    }
    defer {
      x += 1
    }
    return next.hashValue == x ? next : nil
  }
```

Does someone have an idea of how to migrate this function ? 
Except this function (I commented it) the code is migrated here : #287

**Comment by dylan** [comment]
Give my branch a shot, it seems to work well in playgrounds.

**Comment by lastMove** [comment]
Oh thanks a lot ! I will try it out :+1:

**Comment by lastMove** [comment]
It works well !

**Comment by JakeLin** [comment]
Great, well done guys 👍👍👍

**Comment by dylan** [comment]
![salute](http://gif.dyli.sh/bruceyes.gif)
