### ISSUE TITLE
referece to the class Outlet

### ISSUE THREAD

**Issue by lopezquekk** [IBAnimatable/IBAnimatable#294]
How can I create an outlet reference from IBanimatable object like a Button or textfield?

**Comment by JakeLin** [comment]
In identity inspector, change the class to AnimatableButton or AnimatableTextField, then connect an IBOutlet, the class will be AnimatableButton or AnimatableTextField, make sure you import IBAnimatable in your ViewController

**Comment by JakeLin** [comment]
@lopezquekk I close this issue now, please let me know if you have any questions.
