### ISSUE TITLE
clipsToBounds not working

### ISSUE THREAD

**Issue by SMFakhir** [IBAnimatable/IBAnimatable#303]
Seems like clipsToBounds not working anymore since the latest release.

**Comment by JakeLin** [comment]
Can you provide more information? For example, provide a small demo app using Cocaopods. With the latest version 2.7 , it should show the issue, with older version, it works fine. Thanks.

**Comment by tbaranes** [comment]
Closing this issue now, let us know if you have any questions.

**Comment by SMFakhir** [comment]
Hi,

Sorry i was quite busy last week. Please refer to attached code as requested.

[AnimtableTest.zip](https://github.com/IBAnimatable/IBAnimatable/files/476198/AnimtableTest.zip)

**Comment by JakeLin** [comment]
@SMFakhir Can you provide some details? I can see the first one is OK and the second one has the problem. But can you provide more details on what's the difference between them? What's your requirement?

![simulator screen shot sep 16 2016 8 11 10 pm](https://cloud.githubusercontent.com/assets/573856/18582708/ccf7e7e6-7c49-11e6-96d5-49b36108e6c2.png)

**Comment by SMFakhir** [comment]
Actually my requirement is more related to first one but i thought it would be good if i provide a variation, well, i kind of requires clipsToBounds to work with corner radius too but as you can see in the second case, it even fails without it, so in both cases the inner view should be cut off. this is exactly happening in 2.6 but latest version doesn't comply anymore.

I don't quite have time to look into the code right now but i would certainly do that when i find some time and make a PR.

On the other hand it would be best if IBAnimatable also provides corner radius to one or more sides.

Thanks.

**Comment by JakeLin** [comment]
@SMFakhir sorry, I still can't what causes this issue. A PR will be appreciated, thanks.

**Comment by JakeLin** [comment]
@SMFakhir I have submitted a PR #343  to address this issue, please have a look when you have time, thanks.

**Comment by retsohuang** [comment]
Hi @JakeLin 

Can you add this fix to version 2.8.1 ?

**Comment by JakeLin** [comment]
Yes, @retsohuang  but I am busy on a talk for Yow Connected tomorrow, I need to do it after. If OK, can I ask you a favor to create a PR to swift2 branch? The change is https://github.com/IBAnimatable/IBAnimatable/pull/343/files#diff-31a58763e1e26ac0a8bd2adf82b0bd4bR72 thanks.
