### ISSUE TITLE
Compile error in Xcode 8.0 GM Seed 

### ISSUE THREAD

**Issue by alexchan1680** [IBAnimatable/IBAnimatable#306]
In `Xcode 8.0 GM_Seed` version,  `IBAnimatable` framework is not compiled with some errors due to _non escaping_ parameters of `AnimatableCompletion`.

May I create pull request with  [My branch](https://github.com/alexiosdev/IBAnimatable/tree/swift3_alex) ?

**Comment by JakeLin** [comment]
Yes, please
