### ISSUE TITLE
New BlurEffectStyle prominent and regular broken iOS 9 compilation on Master

### ISSUE THREAD

**Issue by winkelsdorf** [IBAnimatable/IBAnimatable#328]
Hi,

BlurEffectStyle new enum cases `prominent` and `regular` are breaking compilation for iOS 9 due to a missing version check.

Please adjust the `#available` check to include iOS and _not only iOS Extensions_

``` swift
    case "prominent":
      if #available(iOS 10.0, iOSApplicationExtension 10.0, *) {
        self = .prominent
        return
      }
    case "regular":
      if #available(iOS 10.0, iOSApplicationExtension 10.0, *) {
        self = .regular
        return
      }
```

in BlurEffectStyle.swift, L 28 & 33 on Master.

Cheers,
Frederik

**Comment by JakeLin** [comment]
Thanks, I am on the train at that moment, can you submit a quick PR for it, or I will fix it tonight? 🙏

**Comment by winkelsdorf** [comment]
@JakeLin Thanks, you were quicker 😁 The usual timezone differences ^^

**Comment by JakeLin** [comment]
Hi @winkelsdorf All credits go to @tbaranes , I didn't do it 😉
