### ISSUE TITLE
Example project: 'sharedApplication()' is unavailable Xcode 7.2/7.3-Beta

### ISSUE THREAD

**Issue by foffer** [IBAnimatable/IBAnimatable#33]
Openning `IBAnimatableApp.xcodeproj` (there is no workspace it seems?) I get the following error:

/Users/xxx/Work/Resources/IBAnimatable/IBAnimatable/RootWindowDesignable.swift:18:32: 'sharedApplication()' is unavailable: Use view controller based solutions where appropriate instead.

**Comment by foffer** [comment]
It seems to be related to this: [Apple extensions](https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionOverview.html)

> Some APIs Are Unavailable to App Extensions
> Because of its focused role in the system, an app extension is ineligible to participate in certain activities. An app extension cannot:
> 
> > Access a sharedApplication object, and so cannot use any of the methods on that object

**Comment by JakeLin** [comment]
Thanks, I just temporary disable  `APPLICATION_EXTENSION_API_ONLY` to fix the build. Will try to find a better solution later.

**Comment by foffer** [comment]
Cool, thanks!
