### ISSUE TITLE
issue when pod install

### ISSUE THREAD

**Issue by nadirozgurler** [IBAnimatable/IBAnimatable#335]
When I pod install some following issues appears, something wrong with last changes?

<img width="1273" alt="screen shot 2016-09-20 at 20 15 55" src="https://cloud.githubusercontent.com/assets/7475071/18681296/276e3d0a-7f70-11e6-8f0f-3c521c18f01a.png">

**Comment by JakeLin** [comment]
Can you tell me which Swift version are you using? 2.3 or 3. Which version of IBAnimatable of the pod. 2.8.1 or master? Master is for Swift 3. 2.8.1 is for Swift 2.3.

**Comment by nadirozgurler** [comment]
I am using swift 2.2 and IBAnimatable 2.8.1

**Comment by JakeLin** [comment]
Got it, if you are using Xcode 7, please use release 2.7 .

**Comment by wanaya** [comment]
this still not working, i have Xcode 7.3.1 with swift 2.3 and IBAnimatable 2.8.1 and i have the same issues.

**Comment by JakeLin** [comment]
@wanaya , if you are using Xcode 7.3.1, you are using Swift 2.2 then please use IBAnimatable 2.7.

If you are using Xcode 8, and you are using Swift 2.3 then please use IBAnimatable 2.8.1.

**Comment by JakeLin** [comment]
@wanaya @nadirozgurler I have updated the README.md for this https://github.com/IBAnimatable/IBAnimatable#swift-22-or-23
