### ISSUE TITLE
Failed to set borderside, animationType

### ISSUE THREAD

**Issue by learnwithgabbar** [IBAnimatable/IBAnimatable#337]
Failed to set (borderSide) user defined inspected property on (IBAnimatable.AnimatableView): [<IBAnimatable.AnimatableView 0x102232860> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key borderSide.

**Comment by JakeLin** [comment]
@techmehra please have a look at this PR https://github.com/IBAnimatable/IBAnimatable/pull/332, There is a document for migration. Please let me know if you find any issues.

**Comment by learnwithgabbar** [comment]
@JakeLin I will surely look at this PR #332

**Comment by JakeLin** [comment]
@techmehra I close it now, please let me know if you still have any problem.
