### ISSUE TITLE
Cannot run included playground

### ISSUE THREAD

**Issue by fvvliet** [IBAnimatable/IBAnimatable#34]
Hello Jake,

A very nice framework you created !!!

Playground execution failed: /var/folders/9y/w9x0q7y56s78qtsn8knw_ns80000gp/T/./lldb/1191/playground15.swift:5:8: error: no such module 'IBAnimatable'
import IBAnimatable

Any suggestions (Xcode 7.2) ?
Thanks
Frank

**Comment by tbaranes** [comment]
I was running in the same issue until I read issue #26! Pretty sure you will find your way over there
@JakeLin Maybe you should link the Apple documentation in the README?

**Comment by fvvliet** [comment]
Yep, adding the IBAnimatable.playground to the IBAnimatableApp project did the trick ;-)

**Comment by JakeLin** [comment]
I will document how to use `IBAnimatable` in other projects, first things I need to do are to support package management tools like CocoaPods, Swift Package Manager. I am working on these.
