### ISSUE TITLE
Option to draw border inside / outside

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#340]
With the swift3 implementation we change the way to draw the borders from outside to inside. For me, it introduces some breaking interface. It would be great to have an option to choose how drawing it.

What do you think about it?

**Comment by JakeLin** [comment]
Sure, the user will have more control. How can we add this info, via a new property as enum?

**Comment by tbaranes** [comment]
Do you mean by creating a new enum with a new designable properties... or by duplicating the current borders (AllIn, AllOut, TopIn, TopOut...)?

**Comment by JakeLin** [comment]
I think your idea is better, we may keep the old one mapped to default behaviour like all -> allIn

**Comment by tbaranes** [comment]
Closing, after some tests, it's just how you play with it, but you can have the expected behaviour with the default draw.

**Comment by JakeLin** [comment]
@tbaranes Do you mean we can configure the frame of the view in Storyboard to get the expected effect like border inside or outside? If yes, I think we can keep the current implementation.

**Comment by tbaranes** [comment]
Yes, that's right

**Comment by JakeLin** [comment]
Cool, thanks @tbaranes
