### ISSUE TITLE
Predefined gradient doesn't render in Interface Builder 

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#341]
Not sure it is a bug of iOS 10 or not? It is not rendering in Interface Builder, but it is OK in Simulator.

<img width="362" alt="screen shot 2016-09-26 at 9 38 31 pm" src="https://cloud.githubusercontent.com/assets/573856/18833037/0bbe28f6-8432-11e6-93a4-e61dc5d4b090.png">
in Interface Builder

<img width="382" alt="screen shot 2016-09-26 at 9 38 48 pm" src="https://cloud.githubusercontent.com/assets/573856/18833041/1240024e-8432-11e6-9e76-23324a725cf6.png">
in Simulator

**Comment by gkye** [comment]
Setting `startColor` and `endColor` doesnt render in interface builder either.  :disappointed:

**Comment by JakeLin** [comment]
@gkye not sure it is a bug of Xcode 8 or not. It works in the simulator. Also, works for the first view of the view controller in both Interface Builder and simulator.

**Comment by tbaranes** [comment]
Just tried it, and it's working well for me using the last version of Xcode 🤔

**Comment by JakeLin** [comment]
@tbaranes It is working if we set it to the top view of the view controller. **Xcode version: Version 8.2.1 (8C1002)**


<img width="1137" alt="screen shot 2017-03-06 at 10 16 57 pm" src="https://cloud.githubusercontent.com/assets/573856/23607875/c5966f2a-02ba-11e7-94b9-397471da21b1.png">
Working for the top view of the view controller


<img width="1037" alt="screen shot 2017-03-06 at 10 15 40 pm" src="https://cloud.githubusercontent.com/assets/573856/23607856/acc32ef2-02ba-11e7-8c43-95a23b500ef2.png">
But doesn't work for the non top views in Interface Builder. But works on the simulator. Don't know why. I am still thinking it is a bug of Xcode.

**Comment by tbaranes** [comment]
Got it, definitely a Xcode bug 😬

**Comment by retsohuang** [comment]
Any update on this?

**Comment by SD10** [comment]
@retsohuang I'm not sure how this behaves in Xcode 9, but I still face this problem often in Xcode 8.

**Comment by chrisscholly** [comment]
Same here. On Xcode 9.1.

**Comment by tbaranes** [comment]
Closing this now since it's been a while, let us know if you still have any issues with the latest Xcode version.
