### ISSUE TITLE
No such module 'IBAnimatable' in common.swift

### ISSUE THREAD

**Issue by nico75005** [IBAnimatable/IBAnimatable#345]
This is the bug I have when I compile the IBAnimatable Framework in the demo project. I have the same bug on my project. I run both projects thought despite this error.

![screenshot 2016-09-28 17 13 44](https://cloud.githubusercontent.com/assets/1647328/18900586/521e8e4e-859f-11e6-8a3c-741f9d0ac73e.png)

Any idea ?

**Comment by JakeLin** [comment]
@nico75005 sometimes, Xcode is not very stable. Can you clean and build again?

**Comment by nico75005** [comment]
Yes I did. Indeed, Xcode is unstable most of the time...
