### ISSUE TITLE
Slide a button to the left and slide it back to its original position.

### ISSUE THREAD

**Issue by nico75005** [IBAnimatable/IBAnimatable#346]
I wanted to slide a button to the left, then change its title and slide it back to the right for it to get back to it's original position.

Is it possible to do that with IBAnimatable?

I tried this:

```
button.duration = 0.7
button.animationType = .slide(way: .out, direction: .left)
button.animate() {
    button.setTitle(text, for: .normal)
    button.slide(.out, direction: .right)
}
```

but the second time, I just see it passing by really quick...

**Comment by gkye** [comment]
You could extend the animation duration after the text is changed then perform your second slide animation

**Comment by nico75005** [comment]
What do you mean?

For me, when you do a slide, it basically send the `UIView` away with a certain force, not to a certain point, so when you change the slide, you change the direction and the `UIView` is sent away to this direction but not to a certain point? Am I wrong?

**Comment by gkye** [comment]
I meant you could slide your button back `in` after changing the text. ie.

``` swift
button.animationType = .slide(way: .out, direction: .left)
button.animate() {
    button.setTitle(text, for: .normal)
    button.slide(.in, direction: .right)
}
```

Or if you want to move the view to certain position and back to its original position you can use `moveTo`, i.e

``` swift
let originalPos = button.frame.origin
//Move your button to a certain point.
button.moveTo(x: originalPos.x -90,  y: originalPos.y){
button.setTitle(text, for: .normal)
//Move it back to the original position after text is changed. 
    button.moveTo(x: originalPos.x y: originalPos.y)
}
```

**Comment by nico75005** [comment]
Okay perfect. Didn't actually realise how `.in` and `.out` were actually working.

Thanks a lot.

**Comment by JakeLin** [comment]
Thanks @gkye for answering this question.
