### ISSUE TITLE
Failed to render and update auto layout status

### ISSUE THREAD

**Issue by retsohuang** [IBAnimatable/IBAnimatable#349]
### Expected behavior

Interface Builder render correctly.
### Actual behavior

Failed to rendering in Interface Builder, but it is OK in Simulator.

```
../Storyboards/Main.storyboard: error: IB Designables: Failed to render and update auto layout status for CourseDetailViewController (CJ4-8y-5VL): dlopen(IBAnimatable.framework, 1): Symbol not found: __TMVs20_DisabledRangeIndex_
  Referenced from: IBAnimatable.framework
  Expected in: /Applications/Xcode 8.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Xcode/Overlays/../../../../../../Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/libswiftCore.dylib
 in IBAnimatable.framework
```
#### Xcode Version

Version 8.0 (8A218a)
#### Pod Version

2.8.1
#### Swift Version

2.3

**Comment by JakeLin** [comment]
Thanks for reporting this issue, how do you use IBAnimatable? Via cocapods? Can you re-install the pod? Can you rebuild the project? If the issue still happens, can you upload a demo project with the issue? Thanks.

**Comment by JakeLin** [comment]
I also noticed the tool chain is not right, XcodeDefault.xctoolchain , if you use Swift 2.3 the tool chain should not be default

**Comment by retsohuang** [comment]
I use IBAnimatable via CocoaPods, I have clean and re-install it not work.

Am I missing something on setting toolchain?

**Comment by JakeLin** [comment]
I think it is a general issue not specific for IBANimatable . Is IBAnimatable missing a .swift_version file? I don't know the solution since I can not reproduce this issue. If you can upload a small demo project will help us a lot. Or try to google why Xcode use the wrong tool chain.

**Comment by retsohuang** [comment]
I have clean install Xcode from App Store but it still not working, I can't found anything talking about setting Xcode toolchain.

[This](https://github.com/retsohuang/IBAnimatableBug) is demo project.

And I found [same issue](https://github.com/MengTo/Spring/issues/175) from another project.

**Comment by JakeLin** [comment]
Hi Retso,

Can you have a look at this https://forums.developer.apple.com/thread/63237?
It may fix your issue.

Thanks
Jake

**Comment by retsohuang** [comment]
Hi @JakeLin 

It works,  I did this

``` ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'IBAnimatable'
      target.build_configurations.each do |config|
                config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = ['$(inherited)', '/Applications/Xcode.app/Contents/Developer/Toolchains/Swift_2.3.xctoolchain/usr/lib/swift/iphonesimulator']
      end
    end
end
```
