### ISSUE TITLE
Corner Radius iOS 10/Xcode 8/swift 3

### ISSUE THREAD

**Issue by ksinghal** [IBAnimatable/IBAnimatable#350]
I'm running into an issue where setting the corner radius in storyboard for an imageview does not actually work on the device - it previews correctly in interface builder but does not work in the running app on simulator or device. THis only happened after iOS 10 and I believe it may have something to do with the timing of when corner radius is set. See the link below for some reasons why this may be happening. Thanks for this project - it has accelerated my dev work so much!

http://stackoverflow.com/questions/39503661/cornerradius-stopped-working-in-swift-2-3-ios-10-xcode-8

**Comment by JakeLin** [comment]
Hi, have you tried the code in mater? We have fixed an issue for corner radius in https://github.com/IBAnimatable/IBAnimatable/pull/343 . That may fix you issue too. Also please have a look at a demo project GitHub.com/Jakelin/IBPresentation . It also uses corner radius in iOS 10 without problems. If your issue still happens, please upload a simple demo app and we can address this issue easier, thanks.

**Comment by JakeLin** [comment]
@ksinghal  We have shipped 3.0.1, it has fixed the bug. Close this issue now, please let me know if you have any question.

**Comment by ksinghal** [comment]
Thanks @JakeLin I have fixed the issue by using master, and am happy to see you released the update. This is by far my favorite library thank you so much for your hard work

**Comment by JakeLin** [comment]
@ksinghal no worries, good to hear.
