### ISSUE TITLE
Carthage – no Animatable UI Classes appearing in Storyboard

### ISSUE THREAD

**Issue by terenzeyuen** [IBAnimatable/IBAnimatable#354]
Hi,

I have installed via carthage, but adding AnimatableView as class and IBAnimatable in module has no effect (no fields showing in Storyboard inspector).

Works if I copy the source files folder manually to project but we'd really want to use Carthage.

Please help.

Thanks

**Comment by tbaranes** [comment]
That's a known issue from github, sadly we can't do anything about this.
For more information, you can read the following [carthage issue](https://github.com/Carthage/Carthage/issues/335)

**Comment by terenzeyuen** [comment]
Hm ok, but if we use Swift Package Manager – is this going to be the same? @tbaranes

**Comment by tbaranes** [comment]
I have no idea about this since I never tried, but since it's using frameworks too, there's a big chance that will be the same.
If you try it, let us know I'm curious too know!

**Comment by terenzeyuen** [comment]
I did, doesnt seem to work. :(

So either Pods or manual then?

**Comment by JakeLin** [comment]
CocoaPods works fine, here are some examples https://GitHub.com/Jakelin/IBAwesome https://GitHub.com/Jakelin/IBPresentation

**Comment by terenzeyuen** [comment]
Ok, we are looking to not use Pods in this project. Anyway, had  to use a workaround of Carthage + Workspace. Storyboards are picking them up as well, will stick with this for now. Thanks.

**Comment by tbaranes** [comment]
@terenzeyuen I miss your last comment, what's your workaround to get it working? I'm interesting in a solution since I'm keeping a Podfile just for designable libraries!

**Comment by tbaranes** [comment]
https://github.com/Carthage/Carthage/issues/335

Should we try that last comment?

**Comment by JakeLin** [comment]
@tbaranes yes, worth trying, good find.

**Comment by tbaranes** [comment]
Just tried, but sadly, not working.

**Comment by JakeLin** [comment]
@tbaranes 😥 don't know how https://github.com/toshi0383/RateTV makes it work. There are two more comments said it doesn't work either. Just curious, did you try the `release` configuration? https://github.com/toshi0383/RateTV/pull/8/files#diff-9ec25524da2b844b9faead9e93b88ae9R553

**Comment by tbaranes** [comment]
Interesting case, maybe we can find the solution in this. I didn't try release, but I don't see what that can change?
Anyway, I'm reopening this issue to keep in mind that we still have more solutions explore 🙃

**Comment by JakeLin** [comment]
thanks @tbaranes we may have to wait for Apple to fix that 😢

**Comment by DanielAsher** [comment]
I use `carthage update --use-submodules --no-build --no-use-binaries` and manually add the both the framework project and the framework as an embedded dependency.

This method is robust, and fine-grained, but perhaps not as easy as dragging the built framework into your project.

**Comment by JakeLin** [comment]
@DanielAsher thank you very much for letting us know this solution. Since you shipped test✈️, I believe this solution is solid. Can I ask you a favour to add a side note to the [Carthage section in README.md](https://github.com/IBAnimatable/IBAnimatable/blob/master/README.md#carthage)? Do you know we can modify the README.md on the browser without `git clone`? But I know you have a fork 😉. Thanks.

**Comment by phimage** [comment]
I use carthage too, compile IBAnimatable with it
And yes there is no IBAnimatable classes in storyboard

So I create a workspace with my project and IBAnimatable sources that you can find in Carthage/Checkout by draging and dropping the IBAnimatable project.
The sources are present in workspace but I do not add any target dependencies on my main projet
