### ISSUE TITLE
New 'shared' singleton inaccessible.

### ISSUE THREAD

**Issue by bauermusic** [IBAnimatable/IBAnimatable#363]
Missing `public` before `static let shared = TransitionPresenterManager()`

**Comment by tbaranes** [comment]
😨Thanks for the report! 

I created #364 to fix that. We will release a minor version today or tomorrow, until then, you can target the branch `hotfix/public_singleton` to have a _working_ version.

**Side note:** It would be interesting to add a use case using `TransitionPresenterManager` directly in the example app to avoid that kind of bugs.

**Comment by bauermusic** [comment]
Thanx! Great response time!

**Comment by JakeLin** [comment]
@bauermusic thanks for reporting this issue. Release 3.1.1 is shipped.

Can you tell me why do you use `shared` directly in your code base? Do you subclass `AnimatableModalViewController`? For using those transition animations, we probably don't need to use `PresentationPresenterManager.shared` or `TransitionPresenterManager.shared.retrievePresenter` directly.

**Comment by JakeLin** [comment]
@tbaranes thanks for fixing this issue 👏

**Comment by bauermusic** [comment]
@JakeLin We just use it to control some of the animation properties.

**Comment by JakeLin** [comment]
@bauermusic Do you use the Singleton to retrieve back the animator, then control the properties of the animator? 

Can you have a look at [Proposal: Make PresenterManager Singleton classes `internal`](https://github.com/IBAnimatable/IBAnimatable/issues/365) Does the way (using a delegate) we described in #365 fit your requirement? Because we are thinking to make those Singleton classes to `internal`, your use case can help us understand more whether we should do it or not, thanks.

**Comment by shshalom** [comment]
@JakeLin, Our use case with TransitionPresenterManager is to customize how SlideSegue works and make it fit to our needs.
for example:

``` swift
open class SlideSegue: UIStoryboardSegue {
    
    public var isFade:Bool = true
    public var direction:TransitionAnimationType.Direction = .left
    
    open override func perform() {
        destination.transitioningDelegate = TransitionPresenterManager.shared.retrievePresenter(transitionAnimationType: .slide(to: direction, isFade: isFade), transitionDuration: 0.3)
        
        source.present(destination, animated: true, completion: nil)
    }
}
```

As you can see, it seems simpler that way than doing what is suggested here  [Proposal: Make PresenterManager Singleton classes internal](https://github.com/IBAnimatable/IBAnimatable/issues/365).

Also, I don't think that forcing going in UIKit way is necessarily the right way, I mean I really like using IBAnimatable lib, but if you will "force" my hands into using one way then I would probably would fork the lib, and I don't see the point of doing it. :-/

**Comment by JakeLin** [comment]
@shshalom Thanks for letting me know. Got it, you are making/customizing your own Segue, I didn't think about this use case. I believe it is valid. The user (client code) of the lib should be able to customize segues and use them in **Interface Builder**.

The suggestion I made in  [Proposal: Make PresenterManager Singleton classes internal](https://github.com/IBAnimatable/IBAnimatable/issues/365) is to use the transition animations **programmatically**. And you are using it in **Interface Builder**. They are different.

Thanks, TIL we can customize the segue for `IBAnimatble` further and use them in Interface Builder.
