### ISSUE TITLE
Proposal: Make PresenterManager Singleton classes `internal`

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#365]
## Introduction
`IBAnimatable` library is an extension of Interface Builder and UIKit. aka. Make Interface Builder and UIKit great again. `IBAnimatable` is unlike AsyncDisplayKit to create a pattern to develop iOS app. We should use what UIKit provides. For example, `IBAnimatable` provide a set of custom transition animators, when we use them programmatically, we should use the UIKit's default way via a delegate like
```
extension ViewController: UIViewControllerTransitioningDelegate {
 
}

func animationControllerForPresentedController(
  presented: UIViewController,
  presentingController presenting: UIViewController,
  sourceController source: UIViewController) ->
  UIViewControllerAnimatedTransitioning? {
 
    return FadeAnimator() // More animators can be found in https://github.com/IBAnimatable/IBAnimatable/blob/master/Documentation/Transitions.md and https://github.com/IBAnimatable/IBAnimatable/blob/master/Documentation/Presentations.md
}
```

See [iOS Animation Tutorial: Custom View Controller Presentation Transitions](https://www.raywenderlich.com/113845/ios-animation-tutorial-custom-view-controller-presentation-transitions) for more info about how to use custom animators.

`PresentationPresenterManager`and `TransitionPresenterManager` are two helper classes to help us use custom transition animations in Interface Builder, when we custom transition animators programmatically, we should not use those singleton classes.

## Motivation
Force the user not to use those Singletons and have to use the UIKit's default way via a delegate.

## Proposed solution
Mark them `internal`
- [ ] `PresentationPresenterManager`
- [ ] `TransitionPresenterManager`

## Source compatibility
If we need to implement this proposal. Because It will introduce breaking changes, we need to do it in a major version.

Refer to #363 and #242

**Comment by tbaranes** [comment]
Agree with you. That would be for the best, the only advantage I see to have access at this managers is to do easily custom animations, but it still possible to implement the delegate ourself if necessary (we just have a default implementation).

💯 

Also, if we go for a 4.0, it would be the moment to push all the others breaking change that we want to make (if there's others) 😬

**Comment by JakeLin** [comment]
@shshalom made a great point for this Proposal [New 'shared' singleton inaccessible.](https://github.com/IBAnimatable/IBAnimatable/issues/363#issuecomment-263280635). I am going to close it if there is no objection.

**Comment by JakeLin** [comment]
Because those Singleton classes are used for customizing segue, and we can use the custom segue in Interface Builder. I think we should keep them `public`. I close this issue now.
