### ISSUE TITLE
Works only on simulators not real devices

### ISSUE THREAD

**Issue by Davtyanag** [IBAnimatable/IBAnimatable#376]
Animation doesn't appear on real devices (ios 9, ios 10), but works on simulator. Does anybody know how to fix that? Swift 3, Carthage or manually installed doesn't matter. Nothing helps.

**Comment by JakeLin** [comment]
@Davtyanag Can you provide more info, for example, iPhone 7 + iOS 10, iPhone 6 + iOS 9.2, which animation? How do you use this animation? code, Interface Builder? Thanks.

**Comment by Davtyanag** [comment]
@JakeLin I've tried on iPhone 6 10.2, iPhone 5 9.3, tried in code, also tried in Interface Builder, for instance, I set animation type, and then call animate() function, on simulator everything appears, when I debug on device I see how each method is called and everything looks working, but nothing happens. I don't see any change in animation. Meanwhile tried another library for animation and that one worked.

**Comment by JakeLin** [comment]
@Davtyanag Thanks for following this up for me. That's the first time I hear about this issue. And I am not able to reproduce this issue by myself. Can you please update a small demo app and I can reproduce this issue? Thanks.

One idea is if you create the view manually, do you call `configureAnimatableProperties()`? That may cause the problem if you don't. You can find this example here https://github.com/IBAnimatable/IBAnimatable/blob/master/IBAnimatable.playground/Sources/common.swift#L36

**Comment by Davtyanag** [comment]
@JakeLin yeah! That was an issue configureAnimatableProperties(), thank you very much!

**Comment by JakeLin** [comment]
@Davtyanag good to hear you fix it. I didn't find a good way to call `configureAnimatableProperties` automatically. If you use IB, you don't need to do it. But in code you have to call it.

**Comment by JustinM1** [comment]
@JakeLin Is that in the docs somewhere? I was having trouble with animations not working properly and took me a while before I saw this. Why not override the init in AnimatableView and call configureProperies after making the call to super? 
<img width="1027" alt="ibanimatable" src="https://cloud.githubusercontent.com/assets/18277828/21634449/5d391e98-d225-11e6-8245-115e311d9513.png">
