### ISSUE TITLE
Custom gradient startPoint

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#378]
Probably something like: `.custom(CGPoint, CGPoint)`, or `.custom(startX, startY, endX, endY)`

**Comment by JakeLin** [comment]
@tbaranes do you mean rotate the `startPoint` or it can be the center, inside or outside of the view?

**Comment by tbaranes** [comment]
Just a way to customise where the gradient will start in the view. We can currently start from one of the border, but we have no way to start from X (even if, it's not the center, a border...).
