### ISSUE TITLE
AnimatableCollectionViewCell cornerRadius not working with backgroundColor

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#381]
Here an `AnimatableCollectionViewCell` with a `cornerRadius` set to 12, and a green background color. The dark blue is a subview added. 

![screen shot 2016-12-23 at 09 50 53](https://cloud.githubusercontent.com/assets/1402212/21450246/50fae6ae-c8f5-11e6-9a4f-3473b539c43c.png)

Apparently (I didn't look deeper, will do later if I have time), the cornerRadius is applied to all the subviews (`UIImageView`, `UIVIew`...) but not to the view itself. 

Is that an expected behaviour?

**Comment by JakeLin** [comment]
I think that's related to #377 . It may have some conflict with clipToBounce

**Comment by tbaranes** [comment]
Closing in favor of #377
