### ISSUE TITLE
Where to change to 2.7?

### ISSUE THREAD

**Issue by username1290** [IBAnimatable/IBAnimatable#383]
Hi, the example app mentions: 
1.- Open IBAnimatable.xcodeproj, 
2.- Compile

But where does one change to 2.7 to test on Xcode 7?

**Comment by JakeLin** [comment]
To use Xcode 7 with Swift 2.2, please check out [2.8.1](https://github.com/IBAnimatable/IBAnimatable/releases/tag/2.8.1), it supports Swift 2.3, if it doesn't work, use [2.7](https://github.com/IBAnimatable/IBAnimatable/releases/tag/2.7) instead.

**Comment by username1290** [comment]
Tried both, 2.8.1 and 2.7 on Xcode 7.0 and also on Xcode 7.2.1,
Result: all failed.
Is there anything else that needs to be installed? i.e. a particular iOS simulator version?

**Comment by JakeLin** [comment]
it shouldn't need anything else. How do you use them? Using CocoaPods? What's the error message? I remember 2.7 was built by Xcode 7.3. But I don't have Xcode 7 anymore.

**Comment by username1290** [comment]
Message says "build fail", and a lot of error messages (392)

How do I use them:
1.- Installed Xcode on Yosemite
2.- Downloaded 2.8.1 and 2.7 from your link
3.- Opened the .xcodeproj file
4.- Pressed the Build button.


I also noticed that "Deployment target" says "9.2" but the available simulators to download only are up to 9.1.

Changed "deployment target" to 8.0 and build errors went down to 29.

**Comment by JakeLin** [comment]
@sogen, have you tried Xcode 7.3? Can you use Xcode 8.2? I think most of apps are using Xcode 8 and above.

**Comment by username1290** [comment]
Downloaded 7.3 and 7.3.1 but they don't work in Yosemite...
Guess it's time to update to El Capitan.

Thanks!

**Comment by JakeLin** [comment]
@sogen got it, thanks. If you use El Capitan, it is better to get Xcode 8.2 from App Store and use the latest version of IBAnimatable.

**Comment by tbaranes** [comment]
Closing this now, @sogen don't hesitate to reopen if you still need help!
