### ISSUE TITLE
AnimatableActivityIndicatorView is not displaying in iPad

### ISSUE THREAD

**Issue by ibhavin** [IBAnimatable/IBAnimatable#384]
I have put a `UIView` in my `UIViewController` and give it class to `AnimatableActivityIndicatorView`. In Animation type: `ballRotateChase` and set the color.

Get outlet from storyboard  to viewcontroller file and in `viewDidLoad()` I have start animating by 
`loading.startAnimating()`.

The problem is loader is displaying in simulator but when I run it in iPad it is not displaying. It just displays white `UIView` which I have put. 

Please give solution.

**Comment by lastMove** [comment]
I will try to reproduce your issue.

**Comment by JakeLin** [comment]
@ibhavin It will be great if you can update an example project and specify which iPad / iOS version are you using. Does this issue happen on iPhone or other iPad?

**Comment by ibhavin** [comment]
@JakeLin  I have iPad air 2(9.3.5 iOS version) in which `AnimatableActivityIndicatorView` is not working and in iPhone 6s (10.1 iOS version) it is working.

**Comment by tbaranes** [comment]
Did you try to log the frame of the `AnimatableActivityIndicatorView` or using the inspectable view? 
I'm using myself on iPad and iPhone that class, it's working fine for me, we are gonna need more information to help you with that issue.

**Comment by ibhavin** [comment]
@tbaranes  I have log the frame of the `AnimatableActivityIndicatorView`.

`print(loading.frame)`

**Output:** `(147.0, 293.0, 80.0, 80.0)`

**Comment by tbaranes** [comment]
Sorry for the delay @ibhavin. Can you provide us a sample project in order to reproduce that issue? We are currently not getting it, so it's hard to help you...

**Comment by ibhavin** [comment]
@tbaranes  Here is the demo project:
[IBAnimatable_Demo.zip](https://github.com/IBAnimatable/IBAnimatable/files/736706/IBAnimatable_Demo.zip)

**Comment by tbaranes** [comment]
@ibhavin Sorry again for the delay, I didn't have an iPad at home to test it until recently... 
I tried your sample, and it's working as expected for me. Do you still reproduce it?

**Comment by tbaranes** [comment]
Closing, @ibhavin don't hesitate to reopen that issue if you still need help on this!

**Comment by ibhavin** [comment]
@tbaranes  Don't know why but issue is still there in iPad.
