### ISSUE TITLE
Can I use this by launage of Objective-C? 

### ISSUE THREAD

**Issue by yzcoder** [IBAnimatable/IBAnimatable#390]
In xcode 8.2, I try to use this framework, but xcode show me crash like this
```
xxx.storyboard: error: IB Designables: Failed to render and update auto layout status for xxxController (6Zj-kU-7S5): The agent crashed

xxx.storyboard: error: IB Designables: Failed to update auto layout status: The agent crashed

```
and I can't fix it by myself, please help me.

**Comment by JakeLin** [comment]
@yzcoder Are you using CocoaPods? We don't officially support Objective-C, you can see the [Technical Considerations](https://github.com/IBAnimatable/IBAnimatable/blob/master/Documentation/Roadmap.md#technical-considerations) here. But it may support Objective-C automatically.

**Comment by yzcoder** [comment]
Thanks.
