### ISSUE TITLE
CornerSides is case sensitive

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#394]
For example:`TopLeft` in interface builder won't work.

**Comment by tbaranes** [comment]
That's also the case for `BorderSide`.

**Comment by JakeLin** [comment]
@tbaranes interesting, we do call `lowercased()` like `let sideElements = rawValue.lowercased().characters.split(separator: ",")` in `BorderSides`

**Comment by mmadjer** [comment]
@tbaranes, I double checked the border sides and seems to be fine. Any special case you checked?

**Comment by tbaranes** [comment]
Maybe I've been faked by Xcode update. Let's consider it as a bad report, I will open a new issue if I reproduce it, sorry! 🤕

**Comment by mmadjer** [comment]
no worries @tbaranes. That's how XCode functions..or doesn't function. ;o)
