### ISSUE TITLE
How to connect storyboard and class code?

### ISSUE THREAD

**Issue by XOneto9** [IBAnimatable/IBAnimatable#395]
How can I connect storyboard and programmatically code class?
Now, If I want to use this IBAnimatbale module, then I should change the name of Class and modules in storyboard.
But, If I do that. I don't know how can I connect code?

ex) storyboard tableview using  name is 'AnimatableTableView' but, code class name is 'Aview'
How can I connect?

**Comment by gkye** [comment]
Based on the example given it sounds like you need to connect your code and storyboard using `IBOutlets`. 

- You can create an instance of `AnimatableTableView` in storyboard within your `ViewController`
![capture](https://cloud.githubusercontent.com/assets/14007152/22360356/dfef49d0-e41c-11e6-8455-d73d5585fd98.PNG)

- Assign your `ViewController` to the class you wish to use. In this class you can create `@IBOutlet`s which you can connect later.

```swift
import UIKit
import IBAnimatable

class AView: UIViewController{
  @IBOutlet var myTableView: AnimatableTableView!  
}
```
![capture](https://cloud.githubusercontent.com/assets/14007152/22360463/f88f15c8-e41d-11e6-81fe-bc9cbb71f3d2.PNG)


- Lastly you can connect your `AnimatableTableView` to the `@IBOutlet` created in `AView` by going to the `Connections Inspector` and connecting the tableView in storyboard to the `@IBOutlet` created in your code.
![capture](https://cloud.githubusercontent.com/assets/14007152/22360534/8ab2f744-e41e-11e6-89e2-74359b4e2d44.PNG)

**Comment by XOneto9** [comment]
@gkye wow, Thanks!!
 I hadn't known like this to connect ways. thanks I learn new way how to connect!
also, Rapidly reply to me
thanks! all of


// additionally, is not exist UICollectionViewController of Animatable module?

**Comment by tbaranes** [comment]
Sadly, we currently have no AnimatableCollectionView. We are tracking this in #53, it will come one day 🙃

**Comment by XOneto9** [comment]
@tbaranes It so sad T^T
Thank you so much to rapidly answer to me!
Thanks

**Comment by XOneto9** [comment]
Sorry, Lastly!!!
could you please tell me about TableviewCell class connecting with storyboard??
if I create UITableViewCell class :):)
