### ISSUE TITLE
additional question about tableviewcell connection

### ISSUE THREAD

**Issue by XOneto9** [IBAnimatable/IBAnimatable#396]
Thanks to help me!
Actually, I already ask question smiler to this request.

I'm understand how to connect storyboard with code class. but In Cell class
like class of UITableViewCell, How can I create instance for connecting storyboard of AnimatableTableViewCell?????

ex) class Aview: TableviewCell {
      }
but It is hard to connect both of them which are storyboard and TableviewCell class

Thanks!

**Comment by JakeLin** [comment]
@XOneto9 your question is a general question on how to custom `UITableViewCell`, I suggest you follow this tutorial and try https://www.ralfebert.de/tutorials/ios-swift-uitableviewcontroller/custom-cells/

If you want to use the features in `AnimatableTableViewCell`, then you can change 

```
class FruitTableViewCell: UITableViewCell {
}
```
to
```
class FruitTableViewCell: AnimatableTableViewCell {
}
```

Then, you can use the inspectable properties from `AnimatableTableViewCell`.

**Comment by XOneto9** [comment]
@JakeLin 
Thanks... 

Well,, I'm solving the problem, I have known the way suggested you to me how can I connect as a above answer.

Well now, I'm solved, when I ask you question, I saw the error to my complier in AnimatableTableViewCell

but I'm re try compiling, then the error is removed totally.
because of error, I have wonder of having a other ways to connect storyboard with code of class.

Thanks have a nice days !!!

**Comment by JakeLin** [comment]
@XOneto9 good to hear you have solved the problem. Sometimes, Xcode is very weird. We need to recompile to fix some issues. In the future, you may have to remove something called derived data too 😓. Have a nice day.
