### ISSUE TITLE
borderWidth set to 0 won't remove the current border

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#397]
Steps to reproduce:
- Set a valid border
- Set borderWidth to 0 in order to remove that border
- Expected: no more border, current result: the border is staying there

That issue is due to the following guard in `BorderDesignable`:

```
    guard borderColor != nil, borderWidth > 0 else {
      return
    }
```

I'm not sure what is the right fix here: should we just remove the `borderWidth` check, or reseting the layers when we are in this case?

For now, a workaround is simply to set the `borderColor` to `.clear` instead of changing the `borderWidth`.

**Comment by JakeLin** [comment]
Shall we put 
```
    layer.borderColor = nil
    layer.borderWidth = 0
    layer.sublayers?.filter { $0.name == "borderSideLayer" || $0.name == "borderAllSides" }
      .forEach { $0.removeFromSuperlayer() }
```
in a method internal closure and call it with in the guard as well?
```
guard borderColor != nil, borderWidth > 0 else {
  clearBorder()
  return
}
```

**Comment by tbaranes** [comment]
I think that could be a good move.
