### ISSUE TITLE
Unable to get vibrancyEffectStyle working

### ISSUE THREAD

**Issue by thierrybucco** [IBAnimatable/IBAnimatable#399]
How vibrancyEffectStyle is supposed to work?

My code has no effect.

progressViewContainer.cornerRadius = 8
progressViewContainer.vibrancyEffectStyle = .dark

Do yo have an idea?

Thanks

**Comment by JakeLin** [comment]
@thierrybucco How is `vibrancyEffectStyle` not working, can you put up a simple example project or upload some screenshots? 

There is a technical limitation for `vibrancyEffectStyle`. Please have a look at the documentation comment. 

```
/**
   Vibrancy effect style: `extraLight`, `light`, `dark`, `regular` (iOS 10+) or `prominent` (iOS 10+). Once specify the vibrancy effect style, all subviews of blur effect view will apply this vibrancy effect. The property should set once. Because once we use `UIVisualEffectView`, Apple uses a private class like `_UIVisualEffectContentView` to contain subviews which will change the view hierarchy. After that, we are not able to restore the original view hierarchy. Also, the Auto Layout constraints will be broken when the system change the view hierarchy. We need to manually re-set up the constraints or use Autoresizing masks to layout the subviews.
   */
  var vibrancyEffectStyle: UIBlurEffectStyle? { get set }

```

Looks like you are using it as a `Container`. All elements within it will lose the layout because of the technical constraints.

**Comment by thierrybucco** [comment]
Thanks @JakeLin for your answer.
Here is a screenshot. There is no subviews..

(lldb) po progressViewContainer!
<IBAnimatable.AnimatableView: 0x7f9bc249b2d0; frame = (137.5 251.5; 100 100); opaque = NO; autoresize = RM+BM; layer = <CALayer: 0x618000238fe0>>

![capture d ecran 2017-02-14 a 12 53 55](https://cloud.githubusercontent.com/assets/12764744/22941735/b003fd46-f2b4-11e6-8456-cc3a4444a7e5.png)

**Comment by JakeLin** [comment]
@thierrybucco  haha, you should use `blurEffectStyle` for the blur effect, `vibrancyEffectStyle` is used for the content on top of the blur effect.

**Comment by thierrybucco** [comment]
Oh! Sorry...
Thanks a lot for your help.

**Comment by JakeLin** [comment]
@thierrybucco my pleasure 😉
