### ISSUE TITLE
PresentationConfiguration has no public initialisers.

### ISSUE THREAD

**Issue by mikhailmulyar** [IBAnimatable/IBAnimatable#401]
At the moment it is not possible to use PresentationPresenter for custom UIViewController, not for AnimatableModalViewController. The problem is first in var presentationConfiguration of PresentationPresenter, which is not public and is not assignable, but required to be non nil if you want to use PresentationPresenter. Second thing that PresentationConfiguration has no public initialisers, so it is not possible to create it outside of the module and assign it to var presentationConfiguration of PresentationPresenter

**Comment by tbaranes** [comment]
That's normal, if you want to use a `PresentationConfiguration` directly, you have to pass by `PresentationPresenterManager`'s `retrievePresenter` which will give you a valid since it will handle a cache for you, 

Side notes: as talked in #363, even if we let access to these classes, we don't encourage you to use them. If possible, you should directly use `PresentationPresentedViewController` to make your custom presentation.

**Comment by mikhailmulyar** [comment]
As far as i can see `PresentationPresenterManager` creates `PresentationPresenter` with `presentationConfiguration = nil`. So it is not usable as `UIViewControllerTransitioningDelegate` until you assign some `presentationConfiguration`. `AnimatableModalViewController` assigns presentationConfiguration in its `setupPresenter` method which is internal.

**Comment by tbaranes** [comment]
My bad, I misread your question. I will need more input about your context. Why don't you want to use `AnimatableModalViewController` directly? Can you give us a concrete example of how you will use this flow if we add a public initialiser to `PresentationConfiguration`?

**Comment by mikhailmulyar** [comment]
I have view controller from another framework, so i can not subclass AnimatableModalViewController. But i want to use PresentationPresenter features to allow presentation features of it in my view controller.

**Comment by tbaranes** [comment]
I understand now, that's make sense! I ended opening the project and realise that's an implementation error. I mixed up the usage of the presentation feature 😆

Just pushed #402, if you want to give it a try, it should solved your issue.

**Comment by mikhailmulyar** [comment]
`var presentationConfiguration: PresentationConfiguration?` in `PresentationPresenter` should be also public to be able to set it

**Comment by JakeLin** [comment]
@mikhailmulyar thanks for reporting that. <del>We</del> I always think more about how to use `IBAnimatable` in *Interface Builder*, not programmatically, especially how to customize UI elements. 

@tbaranes thanks for responding that quickly, you make the project better and better 👍.
