### ISSUE TITLE
BorderDesignable doesn't smoothly animate when borderSides != .AllSides

### ISSUE THREAD

**Issue by DanielAsher** [IBAnimatable/IBAnimatable#404]
Hi,
thanks for a fantastic framework!

I've noticed that if I use an `AnimatableView` with `borderSides` not equal to `.AllSides` (e.g. `bottom`) that border does not smoothly animate when using `UIView.animate(withDuration:)` on the frame of the view. Instead the border immediately redraws to the target frame size, with the view then smoothly animated to its target frame.

I've read that `path` is an animatable property of `CAShapeLayer`, but I'm not sure whether this is possible using AnimatableView.

This problem is clearly illustrated using a simple playground within the context of IBAnimatable playground:

```
import UIKit
import IBAnimatable
import PlaygroundSupport

let iPhoneView = PhoneView()
PlaygroundPage.current.liveView = iPhoneView

//: Set up the animatable View
let initialPosition = CGPoint(x: 20, y: 100)
let initialSize = CGSize(width: 100, height: 100)
let targetPosition = CGPoint(x: 120, y: 100)
let targetSize = CGSize(width: 200, height: 100)

let view = AnimatableView(frame: 
    CGRect(origin: initialPosition, size: initialSize))
view.backgroundColor = UIColor.cyan
view.borderColor = UIColor.black
view.borderWidth = 10
view.borderSides = .bottom
iPhoneView.addSubview(view)

DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
    UIView.animate(withDuration: 1.0, animations: {
        view.frame.origin = targetPosition
        view.frame.size = targetSize
    })
}
```

<img width="1135" alt="screen shot 2017-02-25 at 23 05 34" src="https://cloud.githubusercontent.com/assets/7915553/23335523/0eaa6b8e-fbaf-11e6-8ce6-91013176a17f.png">

**Comment by tbaranes** [comment]
I have to say that I'm not surprised the animation is not working. The current implementation is reloading the border only after receiving `layoutSubviews`. I'm not sure how we can handle that case since we don't get notify of an animation running (do we?).

The best case I can think of right now is that you trigger a `layoutSubviews` in the animation closure, but even using that tricks, I don't think it will animate the drawing path...

Let's think how we can perform that animation properly, it's definitely a nice feature to have.

**Comment by DanielAsher** [comment]
@tbaranes I would assume this applies to all custom drawing features within IBAnimatable - I understand how difficult this could be to solve, though I would suggest that this would be a real barrier to using in any environment that required a mixture of designer and programmatic animation.

Perhaps this could be clearly outlined in the read me.

thanks again for such a rapid response.

**Comment by tbaranes** [comment]
Yeah, we have currently no support for animated the drawing features. If you are interested to work on this, let us know if we can help!

**Comment by JakeLin** [comment]
@DanielAsher maybe off the topic, is it possible just an issue of the playground? Did you try that on a simulator or device? Sometimes, I found out the animations on the playground are quite leggy.

**Comment by DanielAsher** [comment]
This happens also in the simulator (I saw it there first)
