### ISSUE TITLE
CheckBox Button in Dynamic TableView

### ISSUE THREAD

**Issue by DonBaronFactory** [IBAnimatable/IBAnimatable#410]
Hi, I'm experiencing a weird behavior with AnimatableCheckBox within a dynamic TableView.

The checkbox is part of a custom cell (with always the same identifier) and is populated dynamically in a simple UITableView.

While the checkbox works as advertised when the user clicks on it, something else and weird happens within the tableview. 

Say I have a tableview with 20 rows in total but only 10 visible. If I now click on the checkbox in row 2, it correctly sets the checkbox to checked. BUT when I scroll down the tableview and start revealing the previously hidden cells, I see that the checkbox in row 12 has also been set checked.

It basically always also checks the checkbox at the same index + visible cells in the hidden cells

Any Idea whether this is related to IBAnimatable and the way it handles the touchupinside event of the CheckBox?

thanks for help

**Comment by tbaranes** [comment]
It's normal, `UITableView` will reuse all your cells once they aren't visible anymore. If you clicked your row 2, that same row will be reuse as 12, 22... 

You have to configure your cell each time `tableView(UITableView, :cellForRowAt:` is called. In that method, you can configure again your cell, including wether your checkbox has been clicked or not. If you do not change the checkbox state, it will keep the same state as at its previous position.

Does that help?

**Comment by DonBaronFactory** [comment]
Thanks for the hint, although I do understand the basics of what you're saying, I'm not sure what you mean by configure each time. Does that mean I can't use the same cell identifier for each cell? How would the code look like the way you mean it?

**Comment by tbaranes** [comment]
Your identifier is used to reuse your cells, that's not a problem, it's even recommended!

When the `UITableViewDataSource` is calling `cellForRowAt` each time a cell will be visible, that means if you are displaying 10 cells, then scroll, before showing the eleventh, it will call `cellForRowAt` first. In that same method, you can customise your cell: colours, labels, whatever you need to set, it's completely up to you. It's also at this same place you can say to your checkbox "be selected or not"
 
```swift
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let isCheckboxSelected: Bool = // is it selected or not?
        let cell: MyCustomCell = // reuse a cell using your identifier...
        cell.checkbox.state = isCheckboxSelected
       // cell customisation: labels, buttons, colours... whatever you need
        return cell
    }
```

**Note:** I didn't test that code, it may not compiling or the property name may be wrong.

For a deeper understanding of `UITableView` and its cells, I suggest you to read Apple [guides](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/TableView_iPhone/TableViewCells/TableViewCells.html) or just read a few answers on stackoverflow, you will find a lot of information!

**Comment by DonBaronFactory** [comment]
Thanks for the more detailed answer. In fact what you're suggesting is actually what I'm doing right now but it kinda doesn't work as expected. Did it before with UISwitches and it does behave correctly... anyway will keep digging as it really seems not being a problem with IBAnimatable... thanks

**Comment by tbaranes** [comment]
Alright, don't hesitate if you get more information or have any questions!
