### ISSUE TITLE
3.1.3 slideOut are miscalculated

### ISSUE THREAD

**Issue by redent** [IBAnimatable/IBAnimatable#411]
Due to [this change](https://github.com/IBAnimatable/IBAnimatable/commit/12d8261a5ec67878b1861a57526bfca940d5e7d6?_pjax=%23js-repo-pjax-container) introduced in 3.1.3 release, slide out animations are not calculated correctly.

This code:

    @IBOutlet weak var animatableView: AnimatableView!
    
    var viewVisible: Bool = true
    @IBAction func buttonClicked(_ sender: Any) {
        viewVisible = !viewVisible
        
        if viewVisible {
            animatableView.slide(.in, direction: .down)
        }
        else {
            animatableView.slide(.out, direction: .up)
        }
    }

When the `animatableView` is embedded in another view, produces the following result:
![ibanimatableslideissue](https://cloud.githubusercontent.com/assets/1727008/23560111/9762dd2e-0039-11e7-8ae8-dda828919d8b.gif)

The problem is that `minX` and `minY` method of the `frame` makes reference to the local coordinates of the superview, where `screenSize` references the full screen size. To make it work correctly, coordinates must be translated to the window coordinate space:

```
let window = UIApplication.shared.keyWindow!
let frame = window.convert(self.frame, from: superview)
```

This will fix `out` values. `in` values are still incorrect, but they are never used anywhere because `animateIn` uses identity transform and not the input parameters.

**Comment by redent** [comment]
This seems to fix all scenarios:

  ```
func computeValues(way: AnimationType.Way, direction: AnimationType.Direction, shouldScale: Bool) -> AnimationValues {
    let scale = 3 * force
    var scaleX: CGFloat = 1
    var scaleY: CGFloat = 1
 
    let window = UIApplication.shared.keyWindow!
    let frame = window.convert(self.frame, from: superview)
    
    var x: CGFloat = 0
    var y: CGFloat = 0
    switch (way, direction) {
    case (.in, .left), (.out, .right):
      x = screenSize.width - frame.minX
    case (.in, .right), (.out, .left):
      x = -frame.maxX
    case (.in, .up), (.out, .down):
      y = screenSize.height - frame.minY
    case (.in, .down), (.out, .up):
      y = -frame.maxY
    }

    x *= force
    y *= force
    if shouldScale && direction.isVertical() {
      scaleY = scale
    } else if shouldScale {
      scaleX = scale
    }
    
    return (x: x, y: y, scaleX: scaleX, scaleY: scaleY)
  }
```

It can be tested with this code:

```
class ViewController: UIViewController {
    
    @IBOutlet weak var animatableView: AnimatableView!
    
    var viewVisible: Bool = true
    var direction: AnimationType.Direction = .up
    
    @IBAction func buttonClicked(_ sender: Any) {
        viewVisible = !viewVisible
        
        if viewVisible {
            direction = nextDirection()
            animatableView.slide(.in, direction: direction)
        }
        else {
            animatableView.slide(.out, direction: direction)
        }
    }
    
    func nextDirection() -> AnimationType.Direction {
        switch direction {
        case .up:
            return .right
        case .right:
            return .down
        case .down:
            return .left
        case .left:
            return .up
        }
    }
    
}
```

**Comment by tbaranes** [comment]
Oh you are right, didn't think about that case when I fixed that issue 😑
Thanks for the explanation, and looking for a fix! Can you make a PR including that fix?
