### ISSUE TITLE
BackgroundImageDesignable not working

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#428]
I wanted to go ahead by finalising (docs and example) `BackgroundImageDesignable`, but when reading the code, something seems off to me: we create a view, but we don't add / remove it anywhere. So, I tried it (in case I missed something), but it didn't work (normal or bad usage?). Is that expected @phimage ?

Also, while writing the documentation, I started to wondering why is `BackgroundDesignable` necessary? It's just adding an `UIView` for the `BackgroundImageDesignable`, so why not letting `BackgroundImageDesignable` that view itself?

Note for the future PRs, I think (wasn't thinking that before) we should definitely not merge before finalising a feature (example, docs, changelog...), otherwise, we are just adding complexity for maintening and getting incoherent / incomplete docs / examples. That said, even if it's in the same PR, we can help each other by working on the same branch!

**Comment by phimage** [comment]
The function to add or remove image view is call in `didSet` of image view field
(like refresh control, that could be too soon if apple do not allow to play with view hierarchy when affecting attributes)

I am testing now on demo app for table cell 
- I go into demo app scene with 4 statics cells (Work, Food,..) 
- remove the ImageViews, children of Content View
- I go to the table cell view and choose a backgroud view
- run the simulator and it seems ok

I will do a test with table too
For table all cells must have clears colors as background
EDIT: it seems ok
xcode 8.3

`BackgroundDesignable` allow to conform to other needs on background view of table and collection views. `BackgroundImageDesignable` is one of them but we could imagine others.

JakeLin comment on it in https://github.com/IBAnimatable/IBAnimatable/pull/416 "It took me a while to understand this..."

**Comment by tbaranes** [comment]
I will test this again following your instruction, I may miss one. Thanks for the explanation! Closing his since it's working for you, I will reopen it if I have more questions :)

It would be interesting to comment the `BackgroundDesignable` since it's not straightforward to understand.
