### ISSUE TITLE
FatalError: "No opposing HollowState for HollowState.none" in playground

### ISSUE THREAD

**Issue by phimage** [IBAnimatable/IBAnimatable#436]
When trying to see all transition animation available I try systemCameraIris 

maybe related to #427 because we get in `SystemTransitionAnimator`

```swift
self.reverseAnimationType = transitionAnimationType.reversed
```

Then in playground the definition is
```swift
    transitionAnimations.append(["SystemCameraIris", "SystemCameraIris(HollowOpen)", "SystemCameraIris(HollowClose)"])
```
instead of 
```swift
    transitionAnimations.append(["SystemCameraIris", "SystemCameraIris(Open)", "SystemCameraIris(Close)"])
```
so we have always `none` type and the `fatalError`

**Comment by tbaranes** [comment]
Oh you are right, I think we should drop the hard code string from the example app in order to avoid this kind of issues. If I remember well the only reason that we had strings instead of the enum type was to set the title in the navigation bar

**Comment by JakeLin** [comment]
I think we used the string values to demonstrate how can we use those values in Interface Builder. If you have a toString method for the enum. We should always use enum in code. Since @SD10 is working on refactoring. The compiler won't give any error on those changes.

**Comment by SD10** [comment]
Ok I'm closing this because it has been taken care of by #438

**Comment by JakeLin** [comment]
@SD10 thanks for taking care of that.
