### ISSUE TITLE
Turn transition animation doesn't work. π stuff

### ISSUE THREAD

**Issue by phimage** [IBAnimatable/IBAnimatable#440]
we have in `TurnAnimator`
```swift
rotate(angle: factor * -.pi * 2)
rotate(angle: factor * .pi * 2)
```
instead of
```swift
rotate(angle: factor * -.pi / 2)
rotate(angle: factor * .pi / 2)
```

Maybe when converting the deprecated `M_PI_2` some mistake happen
I think other `.pi` must be checked

**Comment by tbaranes** [comment]
Introduced in https://github.com/IBAnimatable/IBAnimatable/pull/237/commits/10104cd0a15cfc29d0c38112d5b4b6ad04aa0a3c

As you said, it seems that we have a few more like this one. Do you want to take care of them?

**Comment by phimage** [comment]
Not for the moment, because I am not sure of animation result for Fold and Flip
