### ISSUE TITLE
Remove unnecessary `self.` if possible

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#445]
It is a controversial topic to use `self.` or not within the class, struct or extension. But in our project, we try to not use unnecessary `self.` if possible.

## What is unnecessary `self.`?
If we remove the `self.` , the code still can compile correctly. We call them unnecessary `self.`. For example within a subclass of `UIView`. `self.bounds =.zero` is same as `bounds = .zero`. `self.addSubview(aView)` is same as `addSubview(aView)`.

## Which `.self` can be removed?
If we use the `.self` within a closure, then we can't remove it.

## How to do it?
Search `self.` and see whether we can remove them.

**Comment by SD10** [comment]
I would love to do this it has been silently KILLING me 😃

**Comment by SD10** [comment]
Resolved in #446
