### ISSUE TITLE
TextField Placeholder / Image Programatically 

### ISSUE THREAD

**Issue by DonBaronFactory** [IBAnimatable/IBAnimatable#451]
Hi, I'm facing a weird problem. When I create an AnimatableTextField via IB then all works as expected. In contrast when I create the same Textfield programatically and apply a left image and placeholder, then the latter don't get displayed... 

```
var emailField: AnimatableTextField = {
        var t = AnimatableTextField()
        t.translatesAutoresizingMaskIntoConstraints = false
        t.borderWidth = 1
        t.borderColor = .white
        t.borderSides = .bottom
        t.leftImage = #imageLiteral(resourceName: "email_text")
        t.placeholderColor = .white
        t.placeholderText = "eMail Address"
        t.tintColor = .white
        t.keyboardType = .emailAddress
        return t
    }()
```
Any Idea what I'm doing wrong?

PS: the Borders get displayed properly

**Comment by phimage** [comment]
you do it when? as class attribute? in viewDidLoad of your controller?

sometime user interface code don`t support to be at class initialization
you can make your variable lazy but one time the bug could come back

**Comment by DonBaronFactory** [comment]
I do create these fields as class attributes in a custom UIView... but from what I understand this may be a bug right?

**Comment by phimage** [comment]
I think you could change your code to fix it for the moment

And for IBAnimatable, maybe `configureImages` must be called in `configureAfterLayoutSubviews` and not `configureInspectableProperties`

---

how/when did you add the emailField to the CustomView?

to add an image to the textfield I think component bounds or frame is needed
and if your component is not in view hierarchy or If you don't set a frame size as init then there is some issue

try to set a frame in init of your TextField
or best setup your component after adding it to the view hierarchy

**Comment by DonBaronFactory** [comment]
will be trying out your suggestions... I basically add the textfield to my view (addSubView) during the init of my custom class. The frame as such might be zero, nonetheless I do constrain it in my code using AutoLayout and anchors

**Comment by DonBaronFactory** [comment]
I did manage to make it work by calling `configureImages` after setting the left image of the textfield and its padding... @phimage you mentioned "for the moment", does that mean you'll be fixing it in a future release? if yes, we should mark this issue as bug / enhancement

**Comment by phimage** [comment]
I have no time to reproduce it at the moment so I am not sure about if it is a real bug or wrong use of IBAnimatable
I ask question just to help and to allow someone to reproduce ;-)

**Comment by tbaranes** [comment]
Not sure what the bug is are how to fix it, but I'm able to reproduce it. Thanks for the report @cre8it !

@phimage Moving the `configureImages` to `configureInspectableProperties` will just freeze the app (infinite loop)

**Comment by tbaranes** [comment]
@cre8it #458 should fixed your issue if you want to give it a try. Otherwise, it will be soon available in master

**Comment by DonBaronFactory** [comment]
@tbaranes thank you, I will be trying it out as soon as released in master ... I know many use Storyboard and thus do not encounter this issue, but Storyboards have made our life so difficult over the years and across development teams that we dropped it completely and only work with autolayout programatically ... IBAnimatable though, has become the prime framework we install for every app we develop, so in case we wouldn't have been able to use it without storyboard, it would have ended up in a small disaster ;) but good you guys are supportive and also responsive ... thanks for that

**Comment by mohamadrezakoohkan** [comment]
i founded this in line 18 of IBAnimatable/PlaceholderDesignable
 ` var placeholderText: String? { get { return "" } set {} }`
which returns "" forever.

**Comment by phimage** [comment]
> i founded this in line 18 of IBAnimatable/PlaceholderDesignable
> ` var placeholderText: String? { get { return "" } set {} }`
> which returns "" forever.

You can point a piece of code directly
https://github.com/IBAnimatable/IBAnimatable/blob/4d68ac5ddc523167c188c538b0766a6930b9e43c/Sources/Protocols/Designable/PlaceholderDesignable.swift#L18

`placeholder` is the right attribute, wondering why it is not remapped to placeholderText
