### ISSUE TITLE
MaskDesignable custom Mask

### ISSUE THREAD

**Issue by lastMove** [IBAnimatable/IBAnimatable#464]
Hello All :) 

I would like to add the ability to set a custom Mask using the powerness of MaskDesignable. 
Code is better and simpler than explanation ^^ 
I would like to be able to do this :
```Swift

 view.maskType = .custom() { (bounds) -> UIBezierPath in
      let path = UIBezierPath()

      path.move(to: CGPoint(x: bounds.width / 2.0, y: bounds.origin.y))
      path.addLine(to: CGPoint(x: bounds.width, y: bounds.height))
      path.addLine(to: CGPoint(x: bounds.origin.x, y: bounds.height))
      path.close()
      return path
    }
````

It implies to add this to MaskType :
```Swift 
  case custom(path: (CGRect) -> UIBezierPath)
````
It's better than setting directly a mask. This solution is Autolayout compatible (thanks to MaskDesignable) and doesn't require to subclass multiple UI* Classes .
 
Do you think we should add this to the library or it's too specific ? 
Obviously this will not be available from IB

**Comment by SD10** [comment]
@lastMove could you achieve this by using a closure that returns a `UIBezierPath` or `CAShapeLayer` and calling it immediately? Sorry if not, I'm a noob with drawing code 😑

I mean the whole library is called IBAnimatable, I don't know if we currently have things that aren't available in interface builder, but I think IB compatible is more of the vision. If we don't have this restriction then I'm not opposed to it at all 😃

**Comment by lastMove** [comment]
Yes, It would be ideal but the problematic is that the mask should be adapted to current bounds. Mask are redrawn each time the view's frame change, that's why it has to be a closure, so we can recall it when needed. MaskDesignable will still IB compatible, it's just that we will not be able to use the `custom`  case from IB.

**Comment by tbaranes** [comment]
I think it could be an interesting feature to add even if it's not supported by IB. Even if one of the main goal is to be IB compatible, a lot of people is using it programmatically, so why not makes things easier for everyone?

Beside the feature itself, let's just keep in mind that it's more interesting for the community to add new masks to IBAnimatable than using custom masks. At least, when the mask is reusable by others.

**Comment by lastMove** [comment]
> let's just keep in mind that it's more interesting for the community to add new masks to IBAnimatable

Yes, you are right, I needed some very specific masks. It could be nice to make a lists of useful masks.

**Comment by JakeLin** [comment]
Since IBAnimatable has a lot of decent features to support IB like cornerRadius, mask, shadow, etc. I can see more and more developers are using it programmatically. I like to feature actually. 

I am thinking in the future, we should improve the programmatical API like what we did for Release 4. one issue was mostly asked is shall we automatically call `configureAnimatableProperties` when the users create the `Animatable***` object programmatically.
