### ISSUE TITLE
animate with animation not work

### ISSUE THREAD

**Issue by quanguyen** [IBAnimatable/IBAnimatable#469]
Hi Jake,

I find the chaining syntax in the `IBAnimatable` (as described in `README` - `How to animate programmatically`) beautiful, but failed to implement it.

With my `controller` declared as an `AnimatableView` (`private let controller = AnimatableView()`), I am trying to animate with an animation type but failed as in the picture below:

<img width="612" alt="screen shot 2017-05-01 at 3 50 01 pm" src="https://cloud.githubusercontent.com/assets/11938078/25576088/ae521830-2e86-11e7-9fdc-de522141b0e2.png">

If I fix the error as the compiler suggests, then it raises another error: 

<img width="612" alt="screen shot 2017-05-01 at 3 51 20 pm" src="https://cloud.githubusercontent.com/assets/11938078/25576107/cbf7aea4-2e86-11e7-819a-877a2e595f41.png">

What should I do to use the chaining syntax?

Regards

**Comment by lastMove** [comment]
Hi, 

I just tried this code : 

````Swift
let controller = AnimatableView()
controller.animate(.moveBy(x: 5, y: 3))
````
and it works.

Are you using the latest version ?

**Comment by JakeLin** [comment]
@quanguyen can you have a look at the Swift Playground files. They have some example how to use `.moveBy`. Also, if you init your `AnimatableView` in code, you need to call `configureAnimatableProperties` manually.

**Comment by quanguyen** [comment]
OK. I got it working now.

Earlier, I had not because I passed in a `CGFloat` to `x` and `y`. After reviewing the API, I found that they must be `Double`. 

Thanks

**Comment by JakeLin** [comment]
@quanguyen we may add overloaded methods for it.

**Comment by quanguyen** [comment]
Ok, I see.
