### ISSUE TITLE
New mask types and change proposal

### ISSUE THREAD

**Issue by phimage** [IBAnimatable/IBAnimatable#482]
# Change proposal for faster new mask type implementation

- `MaskType` enum could provide an `UIBezierPath` using a function like this `func bezierPath(for rect: CGRect)`
- Then in `MaskDesignable` we ask the path and call the draw function only one time code

I think also a lot of code to create `UIBezierPath` must done in one `UIBezierPath` `extension` instead of `MaskDesignable` or `MaskType`
For instance
```swift
extension UIBezierPath {
    public convenience init(triangleInRect rect: CGRect) {
        // code from getTriangleBezierPath
    }
}
```
# New mask type

I have already a lot of `UIBezierPath` code to create the following path

- [x]  .heart ❤️ 
- [x]  .drop 💧 
- [x]  .gear(radius, cogs) ⚙️ 
- [x]  .ring(radius) 💍  
- [x]  .superEllipse 💠  https://en.wikipedia.org/wiki/Superellipse
- [x]  .plus ➕ 
- [x]  .crescent 🌙 

You can copy paste the list and checked the one you think that could be useful as mask layer

**Comment by JakeLin** [comment]
@phimage Great, will make an educational game with my son using IBAniamtable soon ❤️❤️❤️

**Comment by phimage** [comment]
Change proposal approved here #517
Implementation of some mask here #518

**Comment by phimage** [comment]
plus and drop #519

**Comment by phimage** [comment]
![mask](https://user-images.githubusercontent.com/8875768/31852101-4681d21c-b672-11e7-865c-368c6d75cfcf.gif)
