### ISSUE TITLE
Replace String with enum for the properties are not using in IB

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#50]
Because `@IBInspectable` in Interface Builder only support certain types. eg. CGFloat, UIColor, String and Int. But can not support enum inherited from `String`. eg. `enum AnimationType: String`.

@lexrus came up a great idea to use enum in programming API and use `String` in IB.

```
#if TARGET_INTERFACE_BUILDER
  /**
    String value of predefined Animation Type, all supported types are in `AnimationType` enum
  */
  var animationType: String? { get set }
#else
  /**
   Predefined Animation Type, all supported types are in `AnimationType` enum
   */
  var animationType: AnimationType? { get set }
  var animationTypeRaw: String? { get set }
#endif
```

Then when the App runs on simulator (not in IB), the compiler actually uses _non_ `TARGET_INTERFACE_BUILDER`. We have to convert the String value in Storyboard to `AnimationType`. Method Swizzling on `NSKeyedUnarchiver` is one way to do that.

I have tried to use Swift protocol extension.

```
// Use Method Swizzling to convert `String` to emun when loading runtime attributes from Storybaord.
// http://nshipster.com/swift-objc-runtime/
public extension NSKeyedUnarchiver {
  public override class func initialize() {
    struct Static {
      static var token: dispatch_once_t = 0
    }

    // make sure this isn't a subclass
    if self !== NSKeyedUnarchiver.self {
      return
    }

    dispatch_once(&Static.token) {
      let originalSelector = Selector("setValue:forUndefinedKey:")
      let swizzledSelector = Selector("iba_setValue:forUndefinedKey:")

      let originalMethod = class_getInstanceMethod(self, originalSelector)
      let swizzledMethod = class_getInstanceMethod(self, swizzledSelector)

      let didAddMethod = class_addMethod(self, originalSelector, method_getImplementation(swizzledMethod), method_getTypeEncoding(swizzledMethod))

      if didAddMethod {
        class_replaceMethod(self, swizzledSelector, method_getImplementation(originalMethod), method_getTypeEncoding(originalMethod))
      } else {
        method_exchangeImplementations(originalMethod, swizzledMethod)
      }
    }
  }

  // MARK: - Method Swizzling
  func iba_setValue(value: AnyObject?, forUndefinedKey key: String) {
    if (key == "animationType") {
      setValue(value, forKey: "animationTypeRaw")
    }
  }
}
```

But `initialize` never gets called.

Then I tried to do it in `didFinishLaunchingWithOptions`

```
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
    // Override point for customization after application launch.

    let originalSelector = Selector("setValue:forUndefinedKey:")
    let swizzledSelector = Selector("iba_setValue:forUndefinedKey:")

    let originalMethod = class_getInstanceMethod(NSKeyedUnarchiver.self, originalSelector)
    let swizzledMethod = class_getInstanceMethod(NSKeyedUnarchiver.self, swizzledSelector)

    let didAddMethod = class_addMethod(NSKeyedUnarchiver.self, originalSelector, method_getImplementation(swizzledMethod), method_getTypeEncoding(swizzledMethod))

    if didAddMethod {
      class_replaceMethod(NSKeyedUnarchiver.self, swizzledSelector, method_getImplementation(originalMethod), method_getTypeEncoding(originalMethod))
    } else {
      method_exchangeImplementations(originalMethod, swizzledMethod)
    }

    return true
  }
```

but `iba_setValue` never gets called.

Then back to @lexrus 's solution to do the Method Swizzling in Objective C.

```
@implementation NSKeyedUnarchiver (IBAnimatable)

- (void)iba_setValue:(id)value forUndefinedKey:(NSString *)key {
  if ([key isEqualToString:@"animationType"]) {
    [self setValue:value forKey:@"animationTypeRaw"];
  }
}

+ (void) load
{
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^{
    SEL originalMethod = @selector( setValue:forUndefinedKey: );
    SEL swizzledMethod = @selector( iba_setValue:forUndefinedKey: );
    method_exchangeImplementations(
                                   class_getInstanceMethod( self, originalMethod ),
                                   class_getInstanceMethod( self, swizzledMethod )
                                   );
  });
}
@end
```

It is working now. And the storyboard is OK.

But once I add `NSKeyedUnarchiver+IBAnimatable.m` file to `IBAnimatable` framework target. Then the  `iba_setValue` (in NSKeyedUnarchiver+IBAnimatable.m) will not get called anymore. 

Here is the changes 
https://github.com/JakeLin/IBAnimatable/compare/4a5e081...feature/support-enum-for-non-ib-api

**Comment by lexrus** [comment]
It's a dirty workaround which should be avoid in the master branch.
The App may crash at runtime if there's another user-defined UIView subclass which has the same IBInspectable `animationType` property but does not has the `animationTypeRaw`.

**Comment by lexrus** [comment]
Is it possible to specify the default NSKeyedUnarchiver for a Storyboard?

**Comment by lexrus** [comment]
Another concept is, since UIView is inherited from NSObject, we can add properties with class_addProperty function via runtime. Then the `animationTypeRaw` is not required.

**Comment by JakeLin** [comment]
@lexrus Method Swizzling is hacky, it pollute all namespace. I tried to use Swift protocol extension to avoid some caveats. for example, create an extension property for `animationTypeRaw`

```
public var animationTypeRaw: String? {
      get {
        return self.animationType.debugDescription
      }
      set {
        self.animationType = AnimationType(rawValue: newValue ?? "")
      }
}
```

to provide default implementation for associating `animationType` and `animationTypeRaw` but Objective C cannot access this Swift extension.

Also, there is no _sealed_ method to prevent the subclass override the default implementation of `animationTypeRaw`. If some one subclass `Animatable` and then have to understand how `animationType` and `animationTypeRaw` work together.

I am still finding the way to balance that and put it on hold at that moment to work on other features.

**Comment by lexrus** [comment]
Agree.
Shall we set a roadmap for what to do next? Or tag priority of each issue?
