### ISSUE TITLE
There is an mistake in v4.0, UITableView dose not have an outlet named delegate.

### ISSUE THREAD

**Issue by jjjjjeffrey** [IBAnimatable/IBAnimatable#505]
i find that v3.0 does not have the mistake.

<img width="1399" alt="2017-07-07 2 10 19" src="https://user-images.githubusercontent.com/4246681/27945172-0f05dee8-631e-11e7-8e76-c12db6f03708.png">

there is only one pod in the Podfile, and didn't include any other code in the project.
<img width="1512" alt="2017-07-07 2 23 57" src="https://user-images.githubusercontent.com/4246681/27945533-01d1f70a-6320-11e7-981f-68fb7bcfb5fa.png">

**Comment by tbaranes** [comment]
I have no idea why is this triggered, but I don't think it's related to IBAnimatable. Do you have a sample project to reproduce your issue?

**Comment by jjjjjeffrey** [comment]
@tbaranes you can create an new project, add only one pod IBAnimatable 4.0, drag an UITableViewController in the storyboard, the mistake will appear

**Comment by tbaranes** [comment]
You are right, there is something off, it's also reproducible for `UITableView` 🤔

**Comment by jjjjjeffrey** [comment]
@tbaranes Any magic in 4.0? 🌚

**Comment by SD10** [comment]
@jjjjjeffrey After building the project this error disappears for me. I can also access the delegate of `UITableView` with no autocomplete error or crashing on a force unwrap.

**Comment by jjjjjeffrey** [comment]
@SD10 it's not work for me, what Xcode version did you used?

**Comment by SD10** [comment]
@jjjjjeffrey Sorry for the delay, I had to make sure I wasn't on Xcode9 beta. 
I used 8.3.2 and this time the error didn't disappear but `UITableView` has a delegate property that is the `UITableViewController`. I tested this by putting a delegate method in for `didSelectRow(at:)` and nil checking the `tableView.delegate` property. Really strange behavior...

**Comment by SD10** [comment]
@jjjjjeffrey I think I've solved this in #506. Thank you for reporting this issue.
