### ISSUE TITLE
.moveBy & .moveTo not working when result of action...

### ISSUE THREAD

**Issue by justbane** [IBAnimatable/IBAnimatable#507]
Hi, having an issue with .moveBy and .moveTo... if I do something like this in viewDidLoad:

`metBar.animate(.moveBy(x: 100, y: 0), duration: (60 / metronome.getFrequency()) / 2, damping: 1.0, velocity: 1.0, force: 1.0)`

it works when the app loads - but if I do the exact same code within a function that is fired by a button... it fails.

`func moveMe() {
     metBar.animate(.moveBy(x: 100, y: 0), duration: (60 / metronome.getFrequency()) / 2, damping: 1.0, velocity: 1.0, force: 1.0)
}`

Not only does it fail but from that point on NONE of the other animations work.

**Comment by JakeLin** [comment]
@justbane according to `Not only does it fail but from that point on NONE of the other animations work.` do you set up the view in IB or in code, if in code, do you call `configureAnimatableProperties()`?

**Comment by justbane** [comment]
Hi Jake, I have created the View in interface builder but I am setting it's settings for the animation in code.  
No I am not calling that function anywhere - I was not aware of that function.  Should I be if I have created the view and added it's constraints in interface builder or is this only shows that are added using addSubview?

**Comment by JakeLin** [comment]
@justbane you can create the View in IB and set up the animation in code. Then you don't need to call `configureAnimatableProperties()`. Because you said noon of the animations works, I was thinking you created the View in code and didn't call `configureAnimatableProperties()`. Can you call `pop`, `shake` or some similar animations which don't change the position? I try to get some info what's happening. Uploading a small demo project will help us to troubleshoot it easier if you have time to do, thanks.

**Comment by justbane** [comment]
Actually, yes... pop, shake and the "stationary" effects do work. If I add the code I mentioned above though they stop working.

**Comment by JakeLin** [comment]
@justbane based on the code you posted above, I can't find out why I am sorry😞

**Comment by SD10** [comment]
@justbane I can't help much because I'm not that familiar with `IBAnimatable`'s animation API. However, if you were able to replicate this issue in a simple example project I would look into debugging it for you.

**Comment by justbane** [comment]
OK, Ill see if I can replicate in a smaller basic proj... or maybe answer my own question :) I'll let you know how it goes!

**Comment by SD10** [comment]
@justbane I just wanted to follow up and see if you were able to resolve this issue?

**Comment by justbane** [comment]
Hi @SD10 - I have not been able to replicate in a basic project but my project still has the issue. I am moving forward with a couple of other features and may return to the issue and dig a little deeper. I will close this out for now until I have more info.

Thanks for checking back!
