### ISSUE TITLE
Use in objective C

### ISSUE THREAD

**Issue by ravi6880** [IBAnimatable/IBAnimatable#509]
I want to use it in objective c , how can i implement it ?

**Comment by JakeLin** [comment]
@ravi6880 as we mentioned in [our Roadmap](https://github.com/IBAnimatable/IBAnimatable/blob/master/Documentation/Roadmap.md#technical-considerations), we don't want to avoid Swift features to support Objective-C. It is heavily using Swift features like `enum` with the pattern matching. `IBAnimatable` may support Objective-C, but not officially support.

Please let me know if you have any other questions, thanks.
