### ISSUE TITLE
ViewControllerDesignable navigation bar glitch

### ISSUE THREAD

**Issue by SMFakhir** [IBAnimatable/IBAnimatable#524]
Hi,

Why we're not using the following method to show/hide navigation bar, the animated way?
`open func setNavigationBarHidden(_ hidden: Bool, animated: Bool)`

there is a glitch comes when using gestures to pop the view controller if we set the navigation bar hidden property

**Comment by JakeLin** [comment]
@SMFakhir sorry, I don't quite get what you mean? do you suggest to use `setNavigationBarHidden(true, true)` when start popping and `setNavigationBarHidden(false, true)` to see the navigation bar again?

**Comment by SMFakhir** [comment]
Yup, that's right.

Though there are some issues we get, like if the current and previous views both hides the navigation bar, then it gets glitchy. There is a way to track the navigation bar among views which can be implemented by ViewControllerDesignable, I'll think of something and raise a pull request.

**Comment by JakeLin** [comment]
@SMFakhir If I remember correctly, this issue started on iOS 10. Please submit an issue and put more details. A PR will be better👍👍👍, thanks

**Comment by tbaranes** [comment]
Duplicate of #305 ?

**Comment by JakeLin** [comment]
@SMFakhir can you close this issue and keep track on #305? Feel free to post anything if you have more ideas
