### ISSUE TITLE
Configure transition duration using segue

### ISSUE THREAD

**Issue by cashmash** [IBAnimatable/IBAnimatable#525]
Hi,

so how can I override the transitionDuration for the Slide Present Animation?

```
override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        segue.destination.transitioningDelegate = TransitionPresenterManager.shared.retrievePresenter(transitionAnimationType: .slide(to: .left, isFade: false), transitionDuration: 0.2, interactiveGestureType: nil)
    }
```

This does not seem to solve it, because that does not override the `segue.destination.transitioningDelegate` that is set in the lib. Any solution how to change the duration (without creating a custom segue)?

Custom Segue:

```
import UIKit
import IBAnimatable

open class PresentSlideFastSegue: UIStoryboardSegue {
    open override func perform() {
        destination.transitioningDelegate = TransitionPresenterManager.shared.retrievePresenter(transitionAnimationType: .slide(to: .left, isFade: false), transitionDuration: 0.2, interactiveGestureType: nil)
        source.present(destination, animated: true, completion: nil)
    }
}
```

**Comment by kodekarim** [comment]
@cashmash  you can change the slide duration from constants files of IBAnimatable, search for `Constants` file and alert the values of `defaultPresentationDuration`, `defaultTransitionDuration` according to your needs

**Comment by JakeLin** [comment]
@cashmash thanks for bringing this question.It is easy to override the duration when we use it in code. Or as you said to create another custom segue like `PresentSlideFastSegue`. As @abdulKarim002 said, you can change the default duration by changing the `Constants`. I don't know any better way 😞. If you figure out one, please let me know. 

When I designed those segues, I'd like to provide a super easy way (just a drag and drop) for the users to use the transition animations in Interface Builder. However, Interface Builder doesn't support `@IBDesignable` for segues. I have to provide the default values for the transition effort e.g. duration. But I also tried to make all components are very easy to be reused in code. If we need to custom them, we can still use the foundation and create the custom one. I think `PresentSlideFastSegue` is a good example 🤣.

**Comment by tbaranes** [comment]
@cashmash @JakeLin I renamed the PR. Not sure if that's a realisable feature, but it would be interesting to dig in!

**Comment by JakeLin** [comment]
@tbaranes It looks like a limitation of Interface Builder, we can't do until Apple adds the support of it.

**Comment by tbaranes** [comment]
Closing for now, will reopen it once Xcode allow us to do it.
