### ISSUE TITLE
AnimatableTextField text not aligned properly

### ISSUE THREAD

**Issue by rscodra** [IBAnimatable/IBAnimatable#537]
If i create a textfield and make it, lets say approx. 40 in height the text will not be aligned properly. Choosing the vertical alignment options has some various effects, centering it (which is what i need) causes the text to be almost completely cut off (depending on the height of the textfield). Any known fix?

**Comment by JakeLin** [comment]
@sambing thanks for reporting that. Do you use `AnimatableTextField` in code or IB? In the demo project, I change the height of the text field in the sign in screen. It looks OK, can you play around that one to apply your configuration? Will it have the same issue you mention?
