### ISSUE TITLE
how to present method in add animations?

### ISSUE THREAD

**Issue by taeyoung4808** [IBAnimatable/IBAnimatable#538]
hi..

i have two storyboard, how to add in animations?
i can't use segment.

this is my code, i want "Explode" Animation.. 

`        let storyboard = UIStoryboard(name: "Alert", bundle: nil)`
`        let settingboard = storyboard.instantiateViewController(withIdentifier: "defaultAlert")`
`        self.present(settingboard, animated: true, completion: nil)`

sorry for my english level....

**Comment by JakeLin** [comment]
@taeyoung4808 if you are not using Segue, I assume you are going to have `Explode` transition in code, you can use it in a normal UIKit way. Please have a look at this tutorial, https://www.raywenderlich.com/173576/ios-animation-tutorial-custom-view-controller-presentation-transitions-3 In the tutorial, there is a custom animator called `PopAnimator`, in `IBAnimatable`, we already create a bunch of animators including `ExplodeAnimator`. You don't need to recreate and just use it. Look at the part in the tutorial.
```
func animationController(forPresented presented: UIViewController, presenting: UIViewController, source: UIViewController) -> UIViewControllerAnimatedTransitioning? {
  return transition
}
```
Plase notice, the tutorial is not up-to-date. You need to fix it using the latest version of Swift.

You can also look at #523 as well, please let me know if you have other question.

**Comment by taeyoung4808** [comment]
@JakeLin Thankyou!
