### ISSUE TITLE
Animations start with delay even if delay is set to 0

### ISSUE THREAD

**Issue by lukas2** [IBAnimatable/IBAnimatable#540]
I have a more complex animation setup and I noticed that IBAnimatable animations are delayed by up to 3 seconds. After some digging I noticed that some layers' CACurrentMediaTime is NOT the same as CACurrentMediaTime called on the UIView object using the animation.

According to apple one should convert the media time from the layer itself. ( https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CoreAnimation_guide/AdvancedAnimationTricks/AdvancedAnimationTricks.html#//apple_ref/doc/uid/TP40004514-CH8-SW2 )

That's what I did and now the timings are correct. I'm posting a PR below.

**Comment by JakeLin** [comment]
Close because of #541  thanks again @lukas2 . Please let me know if you would like to contribute more on IBAnimatable and join us as a core contributor, I can send you an invite, thanks.

**Comment by lukas2** [comment]
@JakeLin Maybe in the future. Right now for me opting in to more work would be irresponsible. ;)

**Comment by JakeLin** [comment]
@lukas2 no worries, please let me know if you would like to join in the future. Thanks again for your PR.
