### ISSUE TITLE
Any thoughts on how to use this great module with custom views which are derived from UIKit views

### ISSUE THREAD

**Issue by tuyendv2** [IBAnimatable/IBAnimatable#55]
I am using this library https://github.com/CosmicMind/Material, and want to have these components integrated with animatable feature in Interface Builder. I think moving forward I also want to have such kind of thing for any other great UI libraries. Do you have any ideas on how to get this done in the generic way.

**Comment by JakeLin** [comment]
@tuyencoder I just had a quick look at https://github.com/CosmicMind/Material, it has its own UI elements like `MaterialButton`, to use both of them, you need to either modify `MaterialButton` to conform to `Animatable` or create a subclass of `MaterialButton` to conform to `Animatable`.

 Material design elements is in the backlog, https://github.com/JakeLin/IBAnimatable/issues/16 `IBAnimatable` protocol extentions should be easy to create Material Design elements. One goal of `IBAnimatable` is to easily extend to create new elements with custom styles.

**Comment by tuyendv2** [comment]
Thanks JakeLin. I think while we are waiting for material design components to be built into IBAnimatable, we should have documentation on how to integrate IBAnimatable with other view frameworks. Of course, what you answered is roughly enough for now.

**Comment by JakeLin** [comment]
@tuyencoder can I ask you a favour to share what you find to put them together by following my comments above? please let me know if you have any questions. Thanks.

**Comment by JakeLin** [comment]
Please see #174 , close this issue now. 

@tuyencoder , please let me know if you have any questions, thanks.
