### ISSUE TITLE
Use code to animate confused me

### ISSUE THREAD

**Issue by weixianlove** [IBAnimatable/IBAnimatable#550]
I has four view in the viewController ,"left and right" are use IBAnimatable,"l and r" are use Spring. When I set the animate in the storyboard, they are almost the same. But when I set the animate by code, Spring maintain the animate, IBA can't work good。

` override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated）

        left.animate(.slide(way: .in, direction: .right))
        right.animate(.slide(way: .in, direction: .left))
        
        l.animation = "slideRight"
        l.animate()
        
        r.animation = "slideLeft"
        r.animate()
        
    }
`
![apr-08-2018 17-27-00](https://user-images.githubusercontent.com/14065957/38465823-f417e046-3b52-11e8-8ae1-0e34eebd7195.gif)

**Comment by JakeLin** [comment]
@weixianlove after you create the view in code, can you call `configureAnimatableProperties` to init the animatable properties?

**Comment by weixianlove** [comment]
@JakeLin 
`    var left: AnimatableView!
    var right: AnimatableView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        left = AnimatableView(frame: CGRect(x: 0, y: 80, width: 150, height: 150))
        left.center.x = view.center.x
        left.backgroundColor = .cyan
        left.configureAnimatableProperties()
        view.addSubview(left)
        
        right = AnimatableView(frame: CGRect(x: 0, y: 290, width: 150, height: 150))
        right.center.x = view.center.x
        right.backgroundColor = .red
        view.addSubview(right)
        right.configureAnimatableProperties()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super .viewWillAppear(animated)
        right.delay(1).then(.slide(way: .in, direction: .left))
        left.delay(1).then(.slide(way: .in, direction: .right))
    }
`

I want know where I was made a mistake, thanks a lot.

**Comment by JakeLin** [comment]
@weixianlove is it working now? When I worked on the lib, I was thinking more on Interface Builder. Since more and more developers are using `IBAnimatable` in code. I am thinking to call `configureAnimatableProperties` in `override init(frame: CGRect)` to set up the inspectable and animatable properties automatically.

**Comment by weixianlove** [comment]
@JakeLin it not work as expected、、、and it worked very well on the lib...But sometimes I need use it in code ....

**Comment by tbaranes** [comment]
Closing this now since it's been a while, let us know if you still have any issues.
