### ISSUE TITLE
cant set the placeholder of textview 

### ISSUE THREAD

**Issue by Raviojha62** [IBAnimatable/IBAnimatable#551]
When i am trying to set the placeholder text of textview from code . its showing error
 cell.textView.placeholderText = "Test"
Error is Ambiguous use of 'placeholderText'

**Comment by SD10** [comment]
@Raviojha62 Please share your code so that we can better assist you

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JakeLin** [comment]
@Raviojha62 are you using another library which also has `placeholderText` property?

**Comment by Raviojha62** [comment]
No[
<img width="924" alt="screen shot 2018-04-19 at 10 59 11 am" src="https://user-images.githubusercontent.com/11419103/38972908-dccc104e-43c0-11e8-8e31-fd159f412ec0.png">
<img width="1111" alt="screen shot 2018-04-19 at 10 59 50 am" src="https://user-images.githubusercontent.com/11419103/38972910-de4222c4-43c0-11e8-9674-9d9452c69be8.png">

](url)

**Comment by Raviojha62** [comment]
i have created a custom tableview cell in which i have put a textview animatableTextView 
Other property works except placeholder

**Comment by JakeLin** [comment]
@Raviojha62 interesting, I don't know why, can you please provide a sample project if possible. Or can you create a method like `setPlaceholderText(text: string) { placeholderText = text }' to get around this issue?

**Comment by retsohuang** [comment]
BTW, It's okay to rename placeholderText to placeholder to align UIKit's naming convention? Or you have another consideration?

**Comment by tbaranes** [comment]
Completely ok, let's discuss this in another issue. Closing this now, let us know if you still have any issues.
