### ISSUE TITLE
 Failed to render and update auto layout status

### ISSUE THREAD

**Issue by mthooyavan** [IBAnimatable/IBAnimatable#552]
I am repeatedly getting this error on all the project storyboards where I uses IBAnimatable, I am not able to render the view.

file:///Users/thooyavan/Desktop/iOS/Channel/Storyboard/Base.lproj/Main.storyboard: error: IB Designables: Failed to render and update auto layout status for ProfileViewController (L9H-io-bch): dlopen(IBAnimatable.framework, 1): no suitable image found.  Did find:
	IBAnimatable.framework: required code signature missing for 'IBAnimatable.framework'

<img width="267" alt="image" src="https://user-images.githubusercontent.com/17001899/38955871-7c7c99fe-4373-11e8-817a-9854014d2bee.png">

**Comment by JakeLin** [comment]
@mthooyavan Are you using `IBAnimatable` via CocoaPods or other ways? Have you tried to restart Xcode? Or remove derived data in Xcode? Can you also have a look at #349 ? They are related.

**Comment by mthooyavan** [comment]
Hi,

I am using cocoapods, and yes I tried restarting the XCode, I tried clearing the DerivedData folder and then starting the Xcode, when I do that the layout is rendered but fails to auto update and that too for a very short period of time, which until the initial build by Xcode is completed, once the build is completed the layout rendering fails.

IBAnimatiable version : 5.0.0

&

Xcode Version : 9.3 (9E145)

**Comment by mthooyavan** [comment]
Hi, tried the resolve in the post #349 but it doesn't solve the issue, Kindly help me out with the same.

**Comment by JakeLin** [comment]
@mthooyavan looks like an Xcode 9.3 issue for using `IBInspectable`. Can you see some crash report under `~/Library/Logs/DiagnosticReports` like `IBDesignablesAgentCocoaTouch_*.crash`? I can't see them, it makes me very hard to troubleshoot the issue. If you have those reports, can you have a look and post some useful info here?

**Comment by mthooyavan** [comment]
I am unable to find those crash logs as I just cleaned everything to try a temporary workaround by downgrading the cocoapods.

Issue seems to be with the Xcode 9.3 update and also Cocoapods 1.5.0

Temporary Workaround is to downgrade the cocoapods to 1.4.0. After the downgrade, restart Xcode, reinstall pods, clean the project and rebuild it. This resolves the issue for now as a workaround.

For your information Kindly go through the below issues "https://github.com/CocoaPods/CocoaPods/issues/7606"

Looks like something has to be resolved to get a permanent resolution for this issue

**Comment by JakeLin** [comment]
@mthooyavan thanks, I will keep an eye on this issue.

**Comment by 1amageek** [comment]
Same issues

**Comment by hanpan1935** [comment]
Same issues

**Comment by tbaranes** [comment]
I'm closing this now, but let us know if that still happens with the latest Xcode version
