### ISSUE TITLE
Update IBAnimatable to Swift 4.1

### ISSUE THREAD

**Issue by SD10** [IBAnimatable/IBAnimatable#555]
We should consider doing a release updating to Swift 4.1 and Xcode 9.3

**Comment by JakeLin** [comment]
@SD10 have you created a release for `INAnimatable` before? Could you like to give it a go? https://github.com/IBAnimatable/IBAnimatable/wiki/How-to-release-a-new-version

**Comment by SD10** [comment]
@JakeLin I don't have access to CocoaPods trunk for IBAnimatable.

BTW, we may want to look at automating the release process with something similar to [Moya's Rake script](https://github.com/Moya/Moya/blob/master/Rakefile) in the future.

It updates the podspec, updates the CHANGELOG, creates the release tag, and all that fun stuff automatically.

**Comment by JakeLin** [comment]
@SD10 I can grant you the access to CocoaPods trunk, please give me your account if you would like to. Let me have a look at Moya's script, can we do it in Swift? Although we already use Ruby like CocoaPods.

**Comment by SD10** [comment]
@JakeLin I'm not sure about using Swift, but I don't think so. I can look into it when I have more time. My CocoaPods trunk email is [removed]

**Comment by JakeLin** [comment]
@SD10 you are the owner now, you can delete the pod and run away 🤣
