### ISSUE TITLE
IBAnimatable Storyboard issue

### ISSUE THREAD

**Issue by ignivashiju** [IBAnimatable/IBAnimatable#556]
In XCode 9.3, i am not able to use IBAnimatable pods. When i opened Storyboard, It throw errors. Please check the attached screenshot for same. I am using version swift 4.1. Any suggestions?

![screen shot 2018-04-20 at 1 06 46 pm](https://user-images.githubusercontent.com/16932010/39041291-1bd05d00-44a6-11e8-9ba5-ed996d435fb9.png)

**Comment by JakeLin** [comment]
@ignivashiju Could you please have a look at #552? there is a known issue of CocoaPods [IBDesignable not works with the frameworks which links with CocoaPods' framework.](https://github.com/CocoaPods/CocoaPods/issues/7606) . There is a walkaround you can use for now, thanks

**Comment by ignivapriya** [comment]
After removing IBAnimatable framework my code runs fine.please don't use this library in xcode 9 and above otherwise u are going to face a lot of difficulties

**Comment by SD10** [comment]
@ignivashiju Sorry to hear you are experiencing difficulties. Can you try adding this to your podfile?
```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'IBAnimatable'
      target.build_configurations.each do |config|
                config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = ['$(inherited)', '/Applications/Xcode.app/Contents/Developer/Toolchains/Swift_2.3.xctoolchain/usr/lib/swift/iphonesimulator']
      end
    end
end
```

**Comment by JakeLin** [comment]
@ignivashiju @ignivapriya please have a look at this comment https://github.com/CocoaPods/CocoaPods/issues/7606#issuecomment-380134668 Downgrading CocoaPods to 1.4 works for most of the people. Hope that can help. Sorry for the inconvenience.

**Comment by tbaranes** [comment]
Closing this now since it's been almost 2 years, but let us know if you still have any issues.
