### ISSUE TITLE
Exit animation

### ISSUE THREAD

**Issue by tuyendv2** [IBAnimatable/IBAnimatable#56]
When working with IBAnimatable, I am thinking of whether I can add an Exit animation when the controller is being dismissed. Actually with this library in place, I have an ambition to design all my apps following animations, effects demonstrated in Presentation softwares such as MS Powerpoint, Apple Keynote.

**Comment by JakeLin** [comment]
Do you mean custom transition for dismiss or pop? That's a part of our roadmap, will focus on transitions this month. https://github.com/JakeLin/IBAnimatable/blob/master/Documentation/Roadmap.md#navigation-and-transitioning-animators
