### ISSUE TITLE
Storyboard Assistant Preview does not render animatable view correctly

### ISSUE THREAD

**Issue by DanielAsher** [IBAnimatable/IBAnimatable#568]
This is probably an Xcode bug, but views with custom `instrinsicContentSize`, `draw`, `drawText` etc are not rendered correctly in the Storyboard Assistant Preview window. Simply opening the window in the example `IBAnimatableApp` shows the problem.

Does anyone have information or a workaround for this?

Feel free to close the issue if there is no experience with this editor window (very useful for localization etc!)

I've filed a radar and open radar: [radar?id=5002444492767232](https://openradar.appspot.com/radar?id=5002444492767232)

<img width="1675" alt="storyboard assistant preview error 2018-06-01 at 19 33 13" src="https://user-images.githubusercontent.com/7915553/40858022-d77ef2b0-65d4-11e8-8ddf-6080ee9d58cb.png">

**Comment by JakeLin** [comment]
Thanks @DanielAsher I hope after WWDC, the new version of Xcode will fix that. And I am thinking to add the`init` function to get around this issue. 

```
  override init(frame: CGRect) {
    super.init(frame: frame)
  }

  required public init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
  }
```

**Comment by DanielAsher** [comment]
Thanks @JakeLin for your quick response. Perhaps filing duplicate radars could help. Let's spread the work. Simply copy [the open radar]( https://openradar.appspot.com/radar?id=5002444492767232) to a new issues here: [https://bugreport.apple.com/web/](https://bugreport.apple.com/web/)

I think the IBAnimatable community is very well placed to provide the force to get this fixed.

**Comment by DanielAsher** [comment]
@JakeLin - could you elaborate on the `override init` workaround?
Would this be required in addition to the bug fix from Apple, or could this work regardless?

**Comment by JakeLin** [comment]
@DanielAsher I tried it before. Some of them started working. But not all of them, I have a branch for it. But I am not sure, without Xcode updates, our changes can fix all of those issues or not? It's very annoying 😞

**Comment by DanielAsher** [comment]
@JakeLin and others - has anyone tried the Xcode 10 beta to see if this has been fixed?
If not, perhaps adding the radar / open radar link to README.md could be an effective way to push this request forcefully to Apple

**Comment by JakeLin** [comment]
@DanielAsher no, I haven't, very busy these days 😞
