### ISSUE TITLE
Change transition background

### ISSUE THREAD

**Issue by jonathansolorzn** [IBAnimatable/IBAnimatable#569]
Hello,

Is there any possible way to change the background color when transitioning from one controller to another via segue?

Currently it displays a black background, but it kinda feels like _old_ for modern apps.

It would feel a more personalized experience, also, is it possible to have a gradient background while transitioning?

Thanks.

**Comment by JakeLin** [comment]
@felixsolorzano if you are using the segues, we don't support custom background yet 😞

**Comment by phimage** [comment]
@JakeLin black color is used somewhere by segue transition or the black means there is no view?

ps: since there is color in asset, if somewhere we use black as default color, we could use instead `UIColor(named: "IBColorForXXX") ?? .black`

**Comment by JakeLin** [comment]
@phimage If I understand correctly, not all the transitions can see the background black color, only some of them like `flip`. `fade` won't' see. It is from default iOS app `window.background`. There is a way to change it. But not customizable from `IBAnimatable` lib.

We can set the `window?.backgroundColor` to any color. Then during the transition, we will see the color. Also, we can change it back to black if we need
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
    window?.backgroundColor = .red
    return true
  }
```

@felixsolorzano can you please have a look that fits your requirement?
