### ISSUE TITLE
Set the Animation Type with parameters through XIB

### ISSUE THREAD

**Issue by JqyModi** [IBAnimatable/IBAnimatable#572]
Set the Animation Type with parameters through XIB, for example: slide(way: way, direction: direction)

**Comment by JakeLin** [comment]
@JqyModi sorry, I didn't see your message, please have a look at https://github.com/IBAnimatable/IBAnimatable/blob/master/Documentation/IBAnimatable%203.0%20Migration%20Guide.md#changes-for-animationtype thanks
