### ISSUE TITLE
NatGeo change center

### ISSUE THREAD

**Issue by edon2005** [IBAnimatable/IBAnimatable#577]
HI, 

First of all thanks for great framework that you develop. 

I found a bug(?) in transition netGeo.

in file ```NatGeoAnimator.swift``` in function ```executeLeftAnimation``` you have  such lines:
```
    let oldFrame = fromLayer.frame
    fromLayer.anchorPoint = CGPoint(x: 0.0, y: 0.5)
    fromLayer.frame = oldFrame
```
these change center of uiview. and when we make dismiss, the center of fromView is changed. And it is not get back to right position. And this call a problem of using another part of application that is based on center of View. 
How it is possible to recover the Center? 

Thanks.

**Comment by edon2005** [comment]
#578

**Comment by JakeLin** [comment]
Thanks @edon2005 , great work

**Comment by edon2005** [comment]
👍
