### ISSUE TITLE
Crash on transition in childViewController

### ISSUE THREAD

**Issue by edon2005** [IBAnimatable/IBAnimatable#579]
Hi guys, 

To have a transition in my app I use next code:
```
            let transitionContext = ContainerTransition(animationType: animationType,
                                                        container: self.rootViewController.view,
                                                        parentViewController: self.rootViewController,
                                                        fromViewController: self.rootViewController.childViewControllers.first,
                                                        toViewController: root,
                                                        completion: { childVC?.setViewControllers([], animated: false) })
            transitionContext.animate()
```
Mostly ```self.rootViewController.childViewControllers.first``` is UINavigationController.
So when the animation try to be executed it is crashed. 
Transition animation that crashed:
Portal

```UIViewControllerHierarchyInconsistency', reason: 'child view controller:<UINavigationController: 0x7fd3dd032800> should have parent view controller:(null) but actual parent is:<UIViewController: 0x7fd3dcc11c80>'```

**Comment by tbaranes** [comment]
Sorry we missed your issue, I'm closing this now since it's been a while, let us know if you still have any issues with the latest Xcode version.
