### ISSUE TITLE
How to code transitions?

### ISSUE THREAD

**Issue by jonathansolorzn** [IBAnimatable/IBAnimatable#581]
I can't find documentation to code the transitions, could you provide an example?, I don't really use segues, I use the coordinator pattern in order to manage my controllers under a navigation controller.

**Comment by JakeLin** [comment]
@felixsolorzano can you have a look at https://github.com/IBAnimatable/IBAnimatable/issues/523#issuecomment-351237405 and the relative issues, let me know if you need anything else, thanks.
