### ISSUE TITLE
Compability to use custom border sides and custom corner sides together

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#582]
In the current implementation, if we set custom corner sides to `CornerDesignable`, we can't use custom border's sides, it fallback automatically to all sides.

**Comment by JakeLin** [comment]
There are a few of options we may be able to fix it.

1. Call `configureCornorRadius` after `configureMask` to let the corner radius takes the priority. And they can't share the same shape layer.
2. Remove the corner radius support from `Mask`.
3. Something may be better but I don't know, I hope that exists.

How do you think @phimage I know you like the feature of putting corner radius within the `Mask`.

**Comment by phimage** [comment]
I didn’t look at the code but why mask could interfere with border side ?

Mask and cornerdesignalble are incompatible but If the mask is none, I expect we do not remove the layer or change layer path (using private subclass type)

**Comment by tbaranes** [comment]
@phimage It interferes because we are using `mask.path` to draw the border instead of using the border's sides path. The main reason for that was too keep the chosen mask, but it has its limitations. 

Here the exception following if we have a mask or not: [BorderDesignable](https://github.com/IBAnimatable/IBAnimatable/blob/master/Sources/Protocols/Designable/BorderDesignable.swift#L60)

> Remove the corner radius support from Mask.

@JakeLin I'm not sure if we really can do that while continuing to support corners sides.
