### ISSUE TITLE
inaccessible due to 'private' protection level

### ISSUE THREAD

**Issue by bharath-dev** [IBAnimatable/IBAnimatable#584]
Recently I updated the cocoa pod and once updated I face the following issue.
![screen shot 2018-08-01 at 11 27 30 pm](https://user-images.githubusercontent.com/16458195/43539608-fc3cb680-95e2-11e8-9d2c-536805bd26dc.png)
What could be the possible reason and how can I clear this issue ?

**Comment by SD10** [comment]
@bharath-dev Where is that code located? These APIs are marked as `private` now. 

Can you provide your `IBAnimatable` version & Swift version?

**Comment by exocode** [comment]
have the same errors: 

IBAnimatable 5.1.0

**Comment by tbaranes** [comment]
I used it recently and was working as expecting, I'm closing now but let me know if you still have an issue.
