### ISSUE TITLE
'Style' is not a member type of 'UIBlurEffect'

### ISSUE THREAD

**Issue by exocode** [IBAnimatable/IBAnimatable#585]
Hi there, 

I just tried to rebuild an old app using  `IBAnimatable 5.1.0`

How to solve that?

```
/IBanimatable/BlurEffectStyle.swift
8: extension UIBlurEffect.Style: IBEnum {   # <---
```

**Comment by JakeLin** [comment]
@exocode which `IBAnimatable` did you use before, we have upgrade the library for a few times. There are some migration document in https://github.com/IBAnimatable/IBAnimatable/tree/master/Documentation, please have a look

**Comment by exocode** [comment]
@JakeLin I used 4.2 before

**Comment by tbaranes** [comment]
I'm getting the same issue using the master version, but I didn't have it before updating, probably getting it because I'm still using swift 4.1
Since I don't have Xcode 10 yet, I don't really know what is the good fix. @djbe any idea?

**Comment by djbe** [comment]
Can you check if `Sources/Common/SwiftSupport.swift` is part of your project (in your pods directory)? The alias is defined there.

**Comment by djbe** [comment]
I just tried `pod try https://github.com/IBAnimatable/IBAnimatable`, and it works without issues in both XCode 9 and 10.
