### ISSUE TITLE
Version 5.2.0 pod install idle

### ISSUE THREAD

**Issue by angelinec** [IBAnimatable/IBAnimatable#591]
<img width="850" alt="screen shot 2018-09-26 at 3 14 42 pm" src="https://user-images.githubusercontent.com/9972417/46063579-d60df580-c19f-11e8-9e53-812f1dab2645.png">
I was stuck at the above process for 10mins and counting. So I terminated the process and pod installed version 5.1.0 instead and no problem encountered. Someone please look into this.

Thank you.

Xcode 9.4.1
Cocoapods 1.5.0

**Comment by JakeLin** [comment]
@angelinec have you tried to install the master? it maybe relagted to #590, I was on leave and will make a release 5.2.1 soon, thanks.

**Comment by JakeLin** [comment]
That should be fixed by [release 5.2.1](https://github.com/IBAnimatable/IBAnimatable/releases/tag/5.2.1) , feel free to re-open it if you think it's not fixed.
