### ISSUE TITLE
Header 'IBAnimatable-Swift.h' not found after pod install for multiple targets

### ISSUE THREAD

**Issue by SerjPridestar** [IBAnimatable/IBAnimatable#593]
## Expected Behavior
The IBAnimatable-Swift.h header should be found and project should compile.

## Current Behavior
After I converted my project to Swift 4.2 on Xcode 10 using the latest version of IBAnimatable (5.2.1), the project fails to compile. It informs be that it can not find the header IBAnimatable-Swift.h. Also it informs me that `Could not build Objective-C module 'IBAnimatable'`. 

At first I thought this was because my project got corrupted from another pod because I forked a project and pointed the pod to my own fork. Also on my own project I noticed duplicate files of that pod for some reason. I tried getting rid of it with removing the pod; however, even after removing it seemed that the files existed in the project. I said to myself, I have no solution but to start over I guess, after starting over and resolving all the issues, I got the same problem with IBAnimatable.

Here is my podfile currently: 

```
target 'TestProject' do
	platform :ios, '11.0'
	use_frameworks!

	pod 'IBAnimatable', '~> 5.2.1'

end

target 'Live Project' do
	platform :ios, '11.0'
	use_frameworks!
	pod 'IBAnimatable', '~> 5.2.1'
end

target 'WatchTestProject Extension' do
	platform :watchos, '4.0'
	use_frameworks!
	Doesn't have IBAnimatable
end
```

I had put the common pods into a

```
def common_pods

end
```

However, I stopped doing that because I had some reasons to believe it might be the reason.

## Steps to Reproduce
Install IBAnimatable through cocoapods for multiple targets.

## Context (Environment)
Xcode version: 10.0 (10A255)
Cocoapods version: 1.5.3
IBAnimatable Version: 5.2.1

**Comment by phimage** [comment]
$(SWIFT_MODULE_NAME)-Swift.h is set in "Objective-C Generated Interface Header Name"

**Comment by SerjPridestar** [comment]
@phimage can you please elaborate with what you mean by that?

**Comment by phimage** [comment]
One of the reason to not have the interface generated is to have nothing in "Objective-C Generated Interface Header Name"
<img width="658" alt="screenshot 2018-09-19 at 08 22 25" src="https://user-images.githubusercontent.com/8875768/45734633-76cf4480-bbe5-11e8-9ebd-81732d954e54.png">

For head code in IBAnimatable there is no issue, $(SWIFT_MODULE_NAME)-Swift.h is set

I do not use Cocoapod so I could not help more
(Carthage also use this interfaceto get swift version  for caching)

**Comment by SerjPridestar** [comment]
@phimage Thank you very much for the clarification! I'll take a look now and see what I can do about it.

**Comment by SerjPridestar** [comment]
Just for reference, I had rolled back to my previous working commit, and now reproduced the pod install and everything. I didn't get the same error; however, I did get this error for IBAnimatable where `UIApplication.shared` was being used"

`shared' is unavailable: Use view controller based solutions where appropriate instead`

The solution to that problem is to go to your pods --> IBAnimatable Target --> Build Settings --> Search `Require Only AppExtension-Safe API` --> Set it to NO
