### ISSUE TITLE
Command CompileSwift failed with a nonzero exit code

### ISSUE THREAD

**Issue by hcole123** [IBAnimatable/IBAnimatable#598]
<img width="651" alt="screen shot 2018-11-05 at 4 44 12 pm" src="https://user-images.githubusercontent.com/30845745/48028671-1c009680-e11a-11e8-940d-00c26cef732f.png">

**Comment by mingsai** [comment]
Fix all of the other errors first. The compiler halts at each error before going to the next one. You can also turn on Whole compilation for the project in debug mode and remember to change the Swift version to the latest one in build settings for both the project and the targets. Also, if this solves the issue feel free to close the issue using the button or ping me back if it doesn't solve the problem.

**Comment by phimage** [comment]
Old issue that could be closed. Just use latest Xcode with latest release
