### ISSUE TITLE
How could I set a corner radius to a Polygon mask image view?

### ISSUE THREAD

**Issue by jonathansolorzn** [IBAnimatable/IBAnimatable#600]
I'm using an `AnimatableImageView` and I set the border width to 15 points, how could I make the corners rounded?

**Comment by JakeLin** [comment]
@felixsolorzano currently, the Polygon doesn't corner radius yet.

**Comment by jonathansolorzn** [comment]
Ok, is it possible to set different colors to each polygon side?

**Comment by JakeLin** [comment]
@felixsolorzano we don't have that feature either yet 😭
