### ISSUE TITLE
Shadow layers added indefinitely

### ISSUE THREAD

**Issue by anas10** [IBAnimatable/IBAnimatable#602]
When I update the constraints on a view programmatically, the shadowLayer of the old frame is still there.
Every time, the view is updated to a different frame, a new CALayer is added.

Steps to reproduce:

- Create a view with autolayout constraints
- Set a shadow via IB
- Update a constraint (i.e. height of the view to make it smaller)
- You will have the shadow correctly applied but the layer from the old frame visible as well

I did some debugging, the layer is not removed when this is done :
https://github.com/IBAnimatable/IBAnimatable/blob/997eb2fa2e2d0087869bd8879c199eb1c5cb70b9/Sources/Protocols/Designable/ShadowDesignable.swift#L108-L110
```
// Remove any previous shadow layer
    view.layer.superlayer?.sublayers?.filter { $0.name == "shadowLayer-\(Unmanaged.passUnretained(self))" }
      .forEach { $0.removeFromSuperlayer() }
```
The reason being that the actual name of the layer in my case was :  
`shadowLayer-Unmanaged<AnimatableView>(_value: <IBAnimatable.AnimatableView: 0x7fb35c86a800; frame = (0 -30; 375 202); autoresize = RM+BM; layer = <CALayer: 0x60000217cae0>>)`

but the updated one had the following name : 
`shadowLayer-Unmanaged<AnimatableView>(_value: <IBAnimatable.AnimatableView: 0x7fb35c86a800; frame = (0 -30; 375 166); autoresize = RM+BM; layer = <CALayer: 0x60000217cae0>>)`

The name contains the frame, so if you update the frame it will not find the layer and thus not remove it.

Any suggestion on how this could be fixed?

**Comment by JakeLin** [comment]
@anas10 thanks for reporting that issue, I didn't know `Unmanaged.passUnretained(self)` returns the value including the frame. The fix would find a way to return a value with the object address like `0x7fb35c86a800`. But I haven't found a way to do it yet. Would you like to investigate the as well? thanks

**Comment by anas10** [comment]
I did some investigation and found out when it was not working.
What I said above may not be the reason.

It fails if you set both the shadow and a corner radius along with corner sides.

I've created a failing example to demonstrate that here: https://github.com/Threestup/IBAnimatable

Run the app > Playground > User Interface -> Shadow

I did not see an obvious solution straight away and I cannot spend much more time on this for now. If you have an idea on how this can be fixed, that would be great.

**Comment by JakeLin** [comment]
@anas10 thanks for investigating this issue, if we change the code like
```
 view.layer.superlayer?.sublayers?.filter { $0.name == "shadowLayer" }
      .forEach { $0.removeFromSuperlayer() }
``` 

and don't add `-\(Unmanaged.passUnretained(self))` to do name, will it fix the problem?

**Comment by anas10** [comment]
Already tried that and it seems like that is not the issue. The frame doesn't seem to impact actually and the shadow is removed properly.

The issue only happens if you also set corners with sides on the view. And this code is called: https://github.com/IBAnimatable/IBAnimatable/blob/997eb2fa2e2d0087869bd8879c199eb1c5cb70b9/Sources/Protocols/Designable/CornerDesignable.swift#L68-L84

If I set the shadow even with corner radius it works as long as all corner sides are set.

**Comment by JakeLin** [comment]
@anas10 thanks, I think you spot on. We should not remove all layers from the view. We need to remove the layers with the name `cornerSideLayer ` like

```
view.layer.superlayer?.sublayers?.filter { $0.name == "cornerSideLayer" }
      .forEach { $0.removeFromSuperlayer() }
```

**Comment by anas10** [comment]
The code you are suggesting won't work in this case as the corner side layer is only a mask that is applied not a layer added to the superlayer.

Anyway, I manage to find a "quick & dirty" fix that works for my use cases.

You can have a look here: https://github.com/Threestup/IBAnimatable/commit/4e01c14420c96900d509cb7b835a26f6769dd531

I don't have much time to try more cases for now, unfortunately.
It would interesting to understand why this happens only if a shadow layer is added as well as a mask set by corner sides.

**Comment by JakeLin** [comment]
@anas10 thanks, I got it, you hide them instead of removing them.
