### ISSUE TITLE
[Question] Able to change label text partway through animation

### ISSUE THREAD

**Issue by Genhain** [IBAnimatable/IBAnimatable#604]
Is anything like this possible in IBAnimatable?

    UIView.transition(with: self.cameraMessageLabel,
                                  duration: 0.25,
                                  options: [.transitionCrossDissolve],
                                  animations: {
                                      self.cameraMessageLabel.text = "Recognizing".localized()
                }) { _ in
                    self.cameraMessageLabel.sizeToFit()
                    self.recognizingActivityView.startAnimating()
                }

i.e changing the text of a label while also animating? #501 has some relevance here

**Comment by tbaranes** [comment]
We currently has no support for text animations, but as you said #501 would be a nice way to let the user more animations when running one. Still, no one started any development on this, so...

**Comment by Genhain** [comment]
> no one started any development on this, so...

ah...

Currently trying to meet a deadline, and i plan to add IBAnimatable to the project soon, so if it's still a pending item by then i'll give it a crack
