### ISSUE TITLE
如何在modelPresent一个控制器的时候自定义IBAnimatioin.animationView的背景色

### ISSUE THREAD

**Issue by snaillovesmile** [IBAnimatable/IBAnimatable#605]
![ae25f7e8f8d5edff72950acadc71fc99](https://user-images.githubusercontent.com/33648940/53621413-64941080-3c31-11e9-82da-7f6fa5f877ef.png)

**Comment by JakeLin** [comment]
@SnailLoveSmile 你找到解决方法了吗？可以通过 `AnimatableModalViewController.backgroundColor` 来设颜色。 

**English translate**
Have you found a solution for it? you can set the background color via setting `AnimatableModalViewController.backgroundColor` . Please let me know if you have any qustions, thanks

**Comment by snaillovesmile** [comment]
嗯嗯, 已经好了,谢谢坚哥于百忙之中给与的帮助
