### ISSUE TITLE
Chaining doesn't work at all

### ISSUE THREAD

**Issue by serejaonly** [IBAnimatable/IBAnimatable#606]
![image](https://user-images.githubusercontent.com/33960459/53891175-d8bc2300-403a-11e9-8cbf-1716020d172d.png)

May be i made something wrong, but inserting ".then"-line changes nothing

I need to hide the view after moving smoothly

**Comment by mingsai** [comment]
Maybe its that call to removeFromSuperview within the closure. Try encapsulating that line of code into a call on the main thread using perhaps Dispatch.main ... If this fixes it don't forget to close out the issue.
