### ISSUE TITLE
CALayerInvalidGeometry CALayer position contains NaN: [nan 11]

### ISSUE THREAD

**Issue by miledaoun** [IBAnimatable/IBAnimatable#607]
Is it possible to remove the NaN default values from the classes. Each time I import the library I have to reset them to valid values so that when initializing it, it does not crash.

**Comment by JakeLin** [comment]
Because we can't apply a default value to the properties within the protocol extension, if you create the Components programmatically, you can call `configureInspectableProperties` and `configureAnimatableProperties` to apply the default values. Please let me know if you have any questions, thanks
