### ISSUE TITLE
AnimatableModalViewController enable userInteraction on previous VC

### ISSUE THREAD

**Issue by avjiang** [IBAnimatable/IBAnimatable#610]
Hello guys, 

I want to ask a question here. 

So I have ViewController A, and I am presenting a half-size of an AnimatableModalViewController on top of the ViewController A. By default, it will block the userInteraction of the viewController A.

Is there any way to show the AnimatableModalViewController with userInteraction enabled for ViewController A? In my case, ViewController A is a scrollView. So, I still want to let the user able to scroll through the ViewController A, while the AnimatableModalViewController is being presented. 

Thank you, and many thanks for this great library!

**Comment by tbaranes** [comment]
Sorry we missed your question. I'm closing this now since it's been a while, let us know if you still have any issues / questions.
