### ISSUE TITLE
Animate rotate infinite?

### ISSUE THREAD

**Issue by RiyanFransen** [IBAnimatable/IBAnimatable#615]
I'm trying to add a rotate animation to a UIImageView. The function calls for a repeat count as Int but previous issues showed it with Float.infinite . 0 and -1 are also not working. 

How is this accomplished? 

`syncImage.animate(.rotate(direction: .cw, repeatCount: <Int>))`

**Comment by mingsai** [comment]
Infinite is forever and that's probably longer than your phone battery will last. This works just fine for me on Swift.

        starter.animate(.rotate(direction: .cw, repeatCount: Int.max))

If that solves the issue, don't forget to close it out.
