### ISSUE TITLE
SwiftUI integration / support

### ISSUE THREAD

**Issue by mingsai** [IBAnimatable/IBAnimatable#620]
Just asking the question that many of us may have - any tips/hints/projections of whether this library can be usable in SwiftUI in any way? For example, SwiftUI leverages UIViewRepresentable, custom ViewModifiers and other constructs that might provide a path to integration. Just curious to know...

**Comment by JakeLin** [comment]
The programming pattern in SwiftUI is quite different from the way we use UIKit/Storyboard etc. I haven't found a way to put them together yet, I think the whole iOS community needs to figure out how the transition going.

**Comment by tbaranes** [comment]
I don't think we should make IBAnimatable supports `SwiftUI` since as said @JakeLin, the pattern is really different. If there's a need of an equivalent of `IBAnimatable` I think it should be a standalone library.
