### ISSUE TITLE
full view gradient (on main view) does not redraw upon screen orientation changing

### ISSUE THREAD

**Issue by ghost** [IBAnimatable/IBAnimatable#627]
The gradient seems to only apply to half the screen when the orientation changes from portrait to landscape. i'm using preset gradients on the main view (AnimatableView).

**Comment by ghost** [comment]
This only seems to happen in a modal sheet (using pod Panmodal) ... odd.

**Comment by JakeLin** [comment]
One of the easy ways I can think of is to call `setNeedsLayout()` to force the view to call `layoutSubviews` which will redraw the `CALayer`.

**Comment by ghost** [comment]
Thanks!!
