### ISSUE TITLE
Is there a mask which rounds certain selected sides?

### ISSUE THREAD

**Issue by ghost** [IBAnimatable/IBAnimatable#628]
For example I have a button (say, width of 100, height of 16). The parameters change by type of device. So for wR, hR, it's say 200 by 32. Now, I can use corner radius and compute it based on the height and set it in viewDidLayoutSubviews, but I was wondering if there's already a way to do this and I'm missing it ...?

**Comment by JakeLin** [comment]
You can set the corner radius on selected sides, please see https://github.com/IBAnimatable/IBAnimatable/blob/master/Documentation/APIs.md#cornerdesignable

but if you want to apply a different number for a different device, you have to do it in code.
