### ISSUE TITLE
Swift Package 6.0 compilation error

### ISSUE THREAD

**Issue by dnguyen07** [IBAnimatable/IBAnimatable#629]
I've created a new project and just add IBAnimatable from swift package 6.0
nothing more nothing less and i have 52 compilation errors.

<img width="263" alt="Image" src="https://user-images.githubusercontent.com/1871777/71854640-11a3a900-30df-11ea-99e7-923d906e6d60.png">

It is targeted for iOS 9.3.5 but same for iOS13.

Any ideas?

Thanks.

**Comment by phimage** [comment]
xcode version? the new last one?

**Comment by dnguyen07** [comment]
Yes, 11.3.1

**Comment by unsigned531** [comment]
Same problem, Xcode 11.3.1, Swift 5.1.

**Comment by mesopelagique** [comment]
> Same problem, Xcode 11.3.1, Swift 5.1.

um not same? swift 5.1, @dnguyen07  talk about swift 6.0

I have many project swiftPM compiled using github action here on github. Do not know the xcode version but the swift is 5.1
https://4d-for-ios.github.io/gallery/#/type/form-list

**Comment by unsigned531** [comment]
@dnguyen07 I fixed this problem through fetching from branch "master" instead of selection specific version.

**Comment by tbaranes** [comment]
This will be fixed with the next version, @contributors I think we should do a new one soon?

**Comment by JakeLin** [comment]
related to #633
