### ISSUE TITLE
is there a mask for semicircle / cords?

### ISSUE THREAD

**Issue by ghost** [IBAnimatable/IBAnimatable#630]
I'd like to use the mask to make a loader. like a circle filling up from bottom.
Using the moon mask is not quite looking as I'd like it to, but it works.
Wondering if this is already supported but I'm missing something..?

**Comment by phimage** [comment]
no there is not

Maybe you can use multiple layer, one with circle mask, and a sublayer that grow inside and with a moving rectangle mask

please close if it answer your question
