### ISSUE TITLE
CFBundleVersion issue while compiling demo code. How to resolve this issue??

### ISSUE THREAD

**Issue by sourabhsharmait** [IBAnimatable/IBAnimatable#631]
![Screenshot 2020-02-04 at 8 06 26 PM](https://user-images.githubusercontent.com/12099495/73754170-fa151a00-4789-11ea-8101-648b3cf8ed26.png)

**Comment by JakeLin** [comment]
@sourabhsharmait can you please which specify which Xcode version are you using? I assume Xcode 11.* because I can see iPhone 11 Pro Max.

**Comment by sourabhsharmait** [comment]
Xcode 11.3.1

**Comment by tbaranes** [comment]
I just tried it, it's working as expected. @sourabhsharmait  You should try one more, I'm closing now but don't hesitate to reopen if it happens again (I suppose you find a solution since it's been 2 months already...)

**Comment by JakeLin** [comment]
this issue should be fixed by c5a7efbe328182ff8b33e6e090c9dd59d94c0ed6
