### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#7]
Support CocoaPods to install `IBAnimatable`.

**Comment by tbaranes** [comment]
Is there a reason to not support CocoaPods yet? Interesting in a PR?

**Comment by ohayon** [comment]
https://github.com/JakeLin/IBAnimatable/pull/35

**Comment by AmmarSaadDine** [comment]
Hi, I can't find the pod in CocoaPods. Is it not supported yet? because the documentation says it supports it.

**Comment by mgrider** [comment]
My guess is that the podspec still needs to be pushed to trunk. More details here: https://guides.cocoapods.org/making/getting-setup-with-trunk.html

**Comment by tbaranes** [comment]
I agree with @mgrider , you can already use the library by specifying the git link in your Podfile:

```
pod 'IBAnimatable', :git => 'https://github.com/JakeLin/IBAnimatable'
```

**Comment by ohayon** [comment]
@mgrider best to do that until @JakeLin pushes it up himself

**Comment by JakeLin** [comment]
Thanks guys, I have pushed to trunk. The data URL is https://raw.githubusercontent.com/CocoaPods/Specs/29d5f9d87eacf899fb61ddfea165da53db2a9623/Specs/IBAnimatable/1.0.1/IBAnimatable.podspec.json

I haven't seen it on https://cocoapods.org/?q=IBAnimatable and but can see it at http://cocoadocs.org/docsets/IBAnimatable/1.0.1

**Comment by AmmarSaadDine** [comment]
Now **pod 'IBAnimatable'** is working fine, thanks!

**Comment by JakeLin** [comment]
It is working now. Thanks to everyone help me with this.
