### ISSUE TITLE
More MaskDesignable

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#8]
Currently, `MaskDesignable` only supports `Circle`, can support more mask like `Triangle` and `Star`.

**Comment by lexrus** [comment]
Triangle mask is easy to support but every triangle must has a direction obviously.

``` swift
enum MaskType {
  ...
  case TriangleUp
  case TriangleDown
  case TriangleLeft
  case TriangleRight
}
```

**Comment by JakeLin** [comment]
One difficulty I am having is to support different parameters with different options. For example, for `Circle`, we don't need an angle for it. But for `Triangle` or `Star`, we may need a starting degree.

I am working on `Star` based on your PR. Will ask your favour to review it once I submit a PR. I cam up an idea to put parameter in the MaskType string. Because IB doesn't support enum as `IBInspectable`'s type, we have to use `String` then convert the `String` to the enum. But we can also put more value than the raw value of the enum. e.g. `Star(6)` for a star with 6 points. That may provide a workaround for similar situation.

**Comment by lexrus** [comment]
Yeah. I were thinking about using associated types but fail back to strings at last.
There's another workaround:

``` swift
#if TARGET_INTERFACE_BUILDER
  @IBInspectable public var maskType: String = ""
  @IBInspectable public var triangleDirection: String = ""
  @IBInspectable public var starPoints: Int = 0
#else
  public var maskType: MaskType = .None
#endif
...

enum TriangleDirection {
  case Up, Right, Down, Left
}

typealias StarPoints = UInt

enum MaskType {
  case None
  case Circle
  case Star(StarPoints)
  case Triangle(TriangleDirection)
}
```

**Comment by JakeLin** [comment]
I really like your idea for 

```
#if TARGET_INTERFACE_BUILDER
  @IBInspectable public var maskType: String = ""
#else
  public var maskType: MaskType = .None
#endif
```

I will try to replace all `String` to actual `enum` in one PR. But will introduce breaking changes to the API when we use them in code.  Thanks again.

**Comment by JakeLin** [comment]
For triangle direction, we already have a property called `rotate` in `RotationDesignable`, I steal this idea from Sketch. Unfortunately, it doesn't render properly in Interface Builder. 

And other concern I have is we will add some non relevant properties showing in Interface Builder. For example, `@IBInspectable public var triangleDirection: String = ""` will only be used when we set `maskType` to `.Triangle`. And we may have other property called `starPoints` for `.Star`. It is what we are doing for `animationType`. Some properties like `repeatCount` can only be used for certain types of animations like `Pop`, `Shake` or `Squeeze`. One thing I want to do is to keep the configuration panel as clean as Sketch. But all elements in Interface Builder are semantic. In Sketch, they are all shapes. IB elements require more settings than Sketch's.

I am open to any suggestions because I am still finding the balance to that and don't mind to introduce breaking changes in early stage. Let's break, fix and move forward faster.

Thank you very much again, I am learning from you every day.

**Comment by JakeLin** [comment]
@lexrus I found out this solution doesn't work.

```
#if TARGET_INTERFACE_BUILDER
  /**
    String value of predefined Animation Type, all supported types are in `AnimationType` enum
  */
  var animationType: String? { get set }
#else
  /**
   Predefined Animation Type, all supported types are in `AnimationType` enum
   */
  var animationType: AnimationType? { get set }
#endif
```

It renders in the Storyboard properly, but it can't enable the animation at runtime. Because the compiler treat `animationType` as enum `AnimationType?` instead of `String?` and that is unset from Interface Builder. It may need Xcode team to fix this issue to support enums inherited from `String` or other types.

**Comment by JakeLin** [comment]
I create a feature branch https://github.com/JakeLin/IBAnimatable/tree/feature/support-enum-for-non-ib-api to play around this.

**Comment by JakeLin** [comment]
I think I forgot to push to https://github.com/JakeLin/IBAnimatable/tree/feature/support-enum-for-non-ib-api  this morning. 😓

**Comment by tbaranes** [comment]
From the #59, I like @JakeLin's idea of `Wave(up,40,10)`, but I'm afraid that will be really hard to understand in some cases. `Wave(up)` or `Star(6)` are easy to get, in these cases, this solution may be the best one. But if we go forward and read `Wave(up,40,10)`: what is `40`? What is `10`? In this last case, we put a lot of importance in the documentation, and blind tests. Maybe it will put too much steps to use?

Another solution could be to create more `views` that inherit of `AnimatableView`:
- `AnimatableWaveView` which add `offset,`width`, and`direction` designable properties
- `AnimatableStarView` which add `nbOfbranches`... 
  I suppose to respect the current interface, we should more play on the designable, but how to make them more specific?

EDIT: Following the thread, shouldn't we renamed the issue to be more explicit?
