### ISSUE TITLE
DesignableGradientView should conform to GradientDesignable

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#81]
`DesignableGradientView` was a temporary view to wrap a layer. need to conform to  `GradientDesignable` protocol.

**Comment by tbaranes** [comment]
`GradientDesignable` should also implement `startPoint` process which is implemented in `DesignableGradientView`

**Comment by JakeLin** [comment]
Yes, move it in `DesignableGradientView`

**Comment by tbaranes** [comment]
It still needs some improvements, but DesignableGradientView conforms to `GradientDesignable`.
Also, the `startPoint` is now working when conforming to `GradientDesignable`.
