### ISSUE TITLE
Improving github workflow

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#85]
It would be great to improve the github workflow:
- A better usage of labels to differentiate the issues, at least the basic ones if we don't create custom labels
- Using milestones to determinate which features should be implemented in the next version
- Something more?

Make this will definitely helps us to priorities and ease the development process.

Any thought?

**Comment by JakeLin** [comment]
I like the workflow, we can start with labels.

**Comment by tbaranes** [comment]
Closing this issue since the first step is done. We can reopen it later if we think it's not enough.
