### ISSUE TITLE
Improving GradientDesignable implementation

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#86]
History that bring this issue: #84  / #81 
Historically, `GradientDesignable` wasn't working even if a subview was conforming the protocol. In order to fix this, we moved all the gradient's intelligence directly in the protocol, by creating creating a sublayer directly in the protocol. Using this new implementation, we can make the API nicer and removed useless views like `DesignableGradientView` (#87)

That solution is working well for basic usage. We still need to improve it in order to support rotation... and if possible, let `GradientDesignable` handle everything itself in order to keep the protocol reusable everywhere, without breaking changes.

Any suggestions?

**Comment by JakeLin** [comment]
Merge in #87

**Comment by tbaranes** [comment]
Final details are discussing, but we can consider this issue fixed.
