### ISSUE TITLE
Makes all fillColor using the right implementation

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#94]
In the current code, I found two different implementation to conform a protocol:
- AnimatableView... implementation:

```
  @IBInspectable public var fillColor: UIColor? {
    didSet {
      configFillColor()
    }
  }

...
```
- AnimatableTableView... implementation:

```
  @IBInspectable public var fillColor: UIColor?
...
```

Shouldn't always be the first option? After some tests, I see that when using the second option, the background will be black even if don't set any color. 

Isn't it a bug?

**Comment by JakeLin** [comment]
First one, , because we need to Change the colour at runtime after the view has loaded. it was a bug for the second one

**Comment by tbaranes** [comment]
Alright, I changed the label and added it to the milestone. Is that should also be applied on opacity... ?

**Comment by JakeLin** [comment]
@tbaranes thanks, great work. I think `opacity` is separate property. Don't need to do anything with that yet.
