### ISSUE TITLE
Bug in the mask star draw

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#95]
<img width="205" alt="screen shot 2016-02-13 at 17 25 04" src="https://cloud.githubusercontent.com/assets/1402212/13029134/a6ad195a-d283-11e5-9c1c-6ae9386711dd.png">

**Comment by lexrus** [comment]
My fault. I should leave the star in the center of the view. Fixed.

**Comment by tbaranes** [comment]
@lexrus I still getting an error using the star: it displays well in interface builder, but not anymore on device / simulator / playground. Any idea? The other mask seems to draw as before.

**Comment by tbaranes** [comment]
@lexrus  I'm getting some weird issues with the star, here the result:
- `Master`
  - Working well in the IB
  - Won't appear in the playground, neither on simulator
- `hotfix/fixed_border_designable` (with the mask border fixed):
  - Working well in the IB
  - Simulator /  Playground: appear at the bottom right (any animations enabled), but only drawing the border

<img width="549" alt="screen shot 2016-02-14 at 17 51 05" src="https://cloud.githubusercontent.com/assets/1402212/13034967/8c095c42-d343-11e5-9525-90881d9bebfb.png">

I will try to get more information, but apparently, the `layer.fillColor` seems not working while drawing the star.

**Comment by lexrus** [comment]
I'm sorry, Tom,

This is the first day on my new job. I'll debug this issue later tonight.

**Comment by tbaranes** [comment]
Thanks @lexrus!
