### ISSUE TITLE
Design a Logo

### ISSUE THREAD

**Issue by lexrus** [IBAnimatable/IBAnimatable#98]
Every popular lib has a nice logo.
This logo may also be used as the icon of the demo App. So that Jake can move the demo App to the first screen page of his iPhone.
Mostly it has a purple background I guess.

**Comment by tbaranes** [comment]
Agree. That would really great!

**Comment by lexrus** [comment]
Here is my concept. What do you think?
![ibanimatableiconpreview](https://cloud.githubusercontent.com/assets/219689/13050554/26b82962-d42f-11e5-9dd3-a84d445af99a.jpg)

**Comment by tbaranes** [comment]
Looks nice :+1:  The pencil is a good idea to represent `IBAnimatable`

**Comment by lexrus** [comment]
Oh, it's not a pencil. :sob:

<img width="134" alt="screen shot 2016-02-15 at 10 11 14 pm" src="https://cloud.githubusercontent.com/assets/219689/13050862/107c82cc-d431-11e5-90c5-fbbf5fdb8e9a.png">

**Comment by lexrus** [comment]
How about this one? You can imagine a visualised tap or an activity indicator.

![ibanimatableiconpreview2](https://cloud.githubusercontent.com/assets/219689/13050882/2a6e2aaa-d431-11e5-8bf4-4c1564413c8f.jpg)

**Comment by tbaranes** [comment]
hmmm... I prefer the first one, the "fake pencil" :laughing: 
Now you mention it, it's a really good idea to take the icon from attributes inspector since it's really the basics of `IBAnimatable`. The second one is talking less about the library.

Anyway, whichever is the centered image is, the background is really cool :+1:

**Comment by lexrus** [comment]
Do you really want a pencil?

Introducing Pencil Plus and Pencil Nano :laughing: 

![ibanimatableiconpreview3](https://cloud.githubusercontent.com/assets/219689/13051533/a1dabb64-d434-11e5-8df3-c4a8a14a8d81.jpg)

**Comment by lexrus** [comment]
Had to sleep. Good night.
![ibanimatablehero 3x](https://cloud.githubusercontent.com/assets/219689/13078609/27491a86-d4fb-11e5-9f6c-2dbc2be61e14.png)
![storyboardpreview](https://cloud.githubusercontent.com/assets/219689/13078965/bf4a7fcc-d4fc-11e5-986b-e2ef85ea3a34.jpg)

**Comment by tbaranes** [comment]
No no, I was talking about the "attributes inspector" which make me think about a pencil (should I complain to Apple? :smiling_imp:), now when I see it in Xcode I have the impression to see a pencil :laughing:

**Comment by JakeLin** [comment]
I like the first one.
